### ISSUE TITLE
How to set how HasNavigationBar=false of RxNavigationPage and Third party nuggets integration

### ISSUE THREAD

**Issue by SarthakGz** [adospace/reactorui-maui#1]
First of all Thank you for this amazing library.I really liked it.

I worked on couple of flutter project as well so it seems very similar just need some clarity on few things.
So in flutter every property of widgets are beings passed as a optional parameter inside constructor but it wasn't the case in reactor right so

How to set properties which does not have extension methods
1. Like HasNavigationBar = false to NaigationPage/RxNavigationPage or want to hide default shell navigation bar from ContentPage as I want to render my own custom navigation bar  I couldn't find any way to do hide shell and content page navigation bar

2. Also can we use any library with reactor-maui like Rg.Plugin.Popup or Library Maintainer need  to do some tweaks to support Reactor-MAUI design pattern

**Comment by adospace** [comment]
In MauiReactor you can adopt both approach:
```csharp
class MyComponent : Component
{
string _myProperty;
MyComponent(string myProperty...)
{
   _myProperty = myProperty;
}
}
```
or
```csharp
class MyComponent : Component
{
string _myProperty;
public MyComponent MyProperty(string myProperty)
{
   _myProperty = myProperty;
   return this;
}
}
```
The latter is what I use because I think is more clear when the component is instantiated (by it's a personal choice):
```csharp
new MyComponent()
    .MyProperty("Hello World!")
```

**Comment by adospace** [comment]
1) Attached properties can be set like this:
```csharp
        return new FlyoutPage
        {
            RenderBody()
        }
        .Flyout(RenderFlyout())
        .IsPresented(() => State.IsFlyoutOpen)
        .OnIsPresentedChanged(isPresented => State.IsFlyoutOpen = isPresented)
        .Set(Microsoft.Maui.Controls.NavigationPage.HasNavigationBarProperty, false);
```

**Comment by adospace** [comment]
2) Third-party libraries must be wrapped in a class deriving from MauiReactor `VisualNode ` class as like any other class you see in the base MauiReactor class library. I'm working on a dotnet tool that creates the wrapper automatically (even if some tweaks could be still required).
I'm going to provide wrappers for some established plugins like Maps

**Comment by SarthakGz** [comment]
Thanks for the clarification
