### ISSUE TITLE
Controls are not showing up inside a Grid.

### ISSUE THREAD

**Issue by ankjin** [adospace/reactorui-maui#11]
I basically have a Grid parent with ScrollView
Grid("*","*")
{ 
  ScrollView 
  {
        Grid("Auto Auto","*")
       {
           Frame
           {
                 Grid 
                 {
                      Label(), // not showing up
                      Label() // not showing up
                  }
            }.GridRow(0),
           Frame
           {
                 Grid
                 {
                      Label(), // not showing up
                      Label() // not showing up
                  }
            }.GridRow(1)
      }
   }
};

here's the link for my repo. Thank you
[repo link](https://github.com/ankjin/MauiReactorTestUI/blob/master/Pages/InvoiceUiPage.cs)

![Fi4MrAbX0AQ44la](https://user-images.githubusercontent.com/99092971/205017615-c524cd37-5d86-4721-957d-b91796b650eb.png)

**Comment by ankjin** [comment]
> Running your app I see this: ![image](https://user-images.githubusercontent.com/10573253/205023473-851b5052-60e7-4b93-b43d-c156a7ee2e7f.png)
> 
> The ClientInfo() returns a Frame with 2 children BUT Frame can contain only one child so you are actually showing just the Label with the text "Nike Product1"
> 
> if I use a panel like the VStack instead it correctly shows both: ![image](https://user-images.githubusercontent.com/10573253/205023988-1486f62d-7826-402d-bcf3-15c8ba4acb19.png)

Yes, on first run of the app that's what I should expect on my screen and that's ok, but after adding some more controls then save... Hot reload will kick in, then if you undo the changes and save again, this what will happen on my screen
![image](https://user-images.githubusercontent.com/99092971/205048644-cafb065c-11dc-4d8a-a288-876effb0059e.png)
 after Hot reload. Also in XAML I will get an error if I put two controls inside a Frame, I should take pay attention on this in c#.

**Comment by ankjin** [comment]
> Running your app I see this: ![image](https://user-images.githubusercontent.com/10573253/205023473-851b5052-60e7-4b93-b43d-c156a7ee2e7f.png)
> 
> The ClientInfo() returns a Frame with 2 children BUT Frame can contain only one child so you are actually showing just the Label with the text "Nike Product1"
> 
> if I use a panel like the VStack instead it correctly shows both: ![image](https://user-images.githubusercontent.com/10573253/205023988-1486f62d-7826-402d-bcf3-15c8ba4acb19.png)

Thank you for pointing that out to me, Frame should only contain one child, and this is exactly the reason why my UI is misbehaving.  I should pay attention on this for MVU because in xaml if you put two child control you will get an error. :)

**Comment by adospace** [comment]
yeah, I thought that throwing an exception, in this case, would have broken the developer workflow when iterating with the hot reload, so I decided to be more tolerant
