### ISSUE TITLE
DevExpress in MauiReactor

### ISSUE THREAD

**Issue by iamnevir** [adospace/reactorui-maui#126]
I am new to MauiReactor and i find it very interesting and want to use it for a long time.
May i ask how to add DevExpress Maui controls to MauiReactor, i used Scaffold to DXCollectionView from DevExpress.Maui.CollectionView but it didn't work as well, the Generate doen't have properties of the original class and i can use them.
Does MauiReactor support to DevExpress?

**Comment by adospace** [comment]
Hi, MauiReactor is built on top of .NET Maui so generally speaking it supports any control that works with MAUI itself, so including DevExpress, SyncFusion, Grial, Telerik etc.
Said that, the integration can be sometimes tricky, especially for complex controls like CollectionViews, DataGrids etc.
The Scaffold attribute tries to generate a general-purpose wrapper that usually works as is, but sometimes it requires further modifications and improvements.

Even if I personally think that in many cases using special libraries is not required to create even complex UIs I recognize that this can be a problem for MauiReactor adoption.

For this reason, I decided to create a repository devoted to containing and sharing wrappers for well-known libraries.

[mauireactor-integration repo](https://github.com/adospace/mauireactor-integration)

The first wrapper I'm going to add is for DevExpress DxCollectionView along with a sample app.

Please create an issue on that repo if you find anything not working on the current implementation or needs more scaffolding.

This is the sample code showing integration for DxCollectionView:
 
```csharp
[Scaffold(typeof(DevExpress.Maui.CollectionView.DXCollectionView), implementItemTemplate: true)]
public partial class DXCollectionView { }

class DxCollectionViewPage : Component
{
    public override VisualNode Render()
    {
        return new ContentPage()
        {
            new DXCollectionView()
                .ItemsSource(new []{ "Item1", "Item2" }, item => new Label(item))
        };
    }
}
```

**Comment by iamnevir** [comment]
it's so cool! thank you for your support sir!
