### ISSUE TITLE
Basic animation 

### ISSUE THREAD

**Issue by Raystorm7** [adospace/reactorui-maui#127]
Hi,
I need to animate a grid components.

With MAUI I can do in this way:

```
MauiControls.Grid g = new();
await g.FadeTo(100, 100, Easing.Linear);
```

but the MauiReactor grid doens't have a metho FadeTo or other [basic animation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/animation/basic).

How can I implement these basic animation?
Or they can be add directly to MauiReactor?

Thank you.

**Comment by Code-DJ** [comment]
@Raystorm7 You can use Opacity:

```csharp
new Grid() // MauiReactor
    .Opacity(State.YourVariable ? 1 : 0)
    .WithAnimation(easing: Easing.Linear, duration: YourSpeed)
```

**Comment by adospace** [comment]
Please take a look at the documentation:  https://adospace.gitbook.io/mauireactor/components/animation
