### ISSUE TITLE
Update MauiReactor

### ISSUE THREAD

**Issue by iamnevir** [adospace/reactorui-maui#131]
I updated mauireactor using cli but then when i create project in my visual studio it is still version 1.0.131. And after I did update using nuget there was problem with ScaffoldGenerator when I used SkiaSharp's SKLottieView
![image](https://github.com/adospace/reactorui-maui/assets/128579399/61e85128-899b-444c-af9a-1782b9675bc1)

**Comment by iamnevir** [comment]
![image](https://github.com/adospace/reactorui-maui/assets/128579399/1c9528fe-9e6a-4239-89b0-315931569daf)

**Comment by adospace** [comment]
do you also scaffold SkAnimatedSurfaceView?
```csharp
[Scaffold(typeof(SkiaSharp.Extended.UI.Controls.SKSurfaceView))]
partial class SKSurfaceView { }

[Scaffold(typeof(SkiaSharp.Extended.UI.Controls.SKAnimatedSurfaceView))]
partial class SKAnimatedSurfaceView { }

[Scaffold(typeof(SkiaSharp.Extended.UI.Controls.SKLottieView))]
partial class SKLottieView { }
```

**Comment by iamnevir** [comment]
thank you it worked well!

**Comment by iamnevir** [comment]
@adospace 
i have a problem with update my old project to MauiReactor 1.0.137 when i build project again
![image](https://github.com/adospace/reactorui-maui/assets/128579399/712c623b-8f7d-4754-a281-9c604498794c)

**Comment by adospace** [comment]
I don't think it is something related to MauiReactor. Rebuilding could probably help ?

**Comment by iamnevir** [comment]
@adospace why when i update MauiReactor my Visual Studio doesn't update the template. it still 1.0.131

**Comment by adospace** [comment]
the template is another thing, to update the template you have to run the following command:
`dotnet new install Reactor.Maui.TemplatePack`

the install or update the template to the latest version
