### ISSUE TITLE
Error SfTextInputLayout + VisualNodeWithAttachedPropertiesExtensions.Set(T, BindableProperty, object)

### ISSUE THREAD

**Issue by dixboss** [adospace/reactorui-maui#134]
```
[Scaffold(typeof(Syncfusion.Maui.Core.SfTextInputLayout))]
public partial class SfTextInputLayout {
    public SfTextInputLayout Content(VisualNode render) { 
        this.Set(Syncfusion.Maui.Core.SfContentView.ContentProperty,
            new MauiControls.DataTemplate(() => TemplateHost.Create(render).NativeElement));
        return this;
    }
}


```
**Erreur	CS0311	Impossible d'utiliser le type 'XXXX.Pages.SfTextInputLayout' comme paramètre de type 'T' dans le type ou la méthode gén**érique 'VisualNodeWithAttachedPropertiesExtensions.Set<T>(T, BindableProperty, object)

**Comment by adospace** [comment]
Hi, please for integration issues refer to the dedicated repository:
https://github.com/adospace/mauireactor-integration

I've added the code to integrate SfTextInputLayout here:
https://github.com/adospace/mauireactor-integration/blob/main/Syncfusion/SfIntApp/Controls/Syncfusion.cs

Example usage:

```csharp
new SfTextInputLayout
{
    new Entry()
}
.Hint("Name")

```
