### ISSUE TITLE
Maui Skeleton

### ISSUE THREAD

**Issue by iamnevir** [adospace/reactorui-maui#136]
How can i use [HorusStudio.Maui.Skeleton](https://www.nuget.org/packages/HorusStudio.Maui.Skeleton/) in maui reactor, this have a little bit different and i cant find the way to use it :<. pls help me!

**Comment by adospace** [comment]
Hi, I've created a new repo for MauiReactor integrations: https://github.com/adospace/mauireactor-integration

I'll add it there
