### ISSUE TITLE
Button Shadow and TextColor does not appear on Android and iOS

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#144]
I was learning more about `reactorui-maui` and try to implement material design button and typography. Shadow doesnot appear on the button:
```csharp
 public Button ElevatedButton(string content)
      => new Button(content)
          .Padding(24)
          .FontSize(14)
          .HeightRequest(40)
          .CornerRadius(20)
          .TextColor(Current.OnBackground)
          .BackgroundColor(Colors.Transparent)
          .Shadow(new Shadow()
              .Brush(Colors.Black)
              .Offset(0,0)
              .Radius(5)
              .Opacity(0.2f));
```
In android all the `TextColor` properties doesn't get apply.
<div style="display:flex">
   <img src="https://github.com/adospace/reactorui-maui/assets/29815096/5c81a96f-92da-4e5e-adc7-441b28b2d38b" width="300"/>
  <img src="https://github.com/adospace/reactorui-maui/assets/29815096/a79e4406-6844-41cb-96e2-86cb59109015" width="300"/>
</div>

<div style="display:flex">
<img src="https://github.com/adospace/reactorui-maui/assets/29815096/13db4610-f310-47f4-b4e8-6a6abc6185e9"  width="300"/>
  <img src="https://github.com/adospace/reactorui-maui/assets/29815096/f32bd675-48df-40ef-9b2a-5f1e0e067b93" width="300" />
</div>

The `Shadow` doesnot get apply on the elevated button.

**Comment by adospace** [comment]
Hi, seems like a general issue rather than a MauiReactor problem, can you confirm that the problem doesn't exist in .NET MAUI itself?

**Comment by cris-m** [comment]
I have checked in MAUI and everything seems fine. I have fixed the `Shadow`  issue. `Offset ` was `0,0`.  The text and icon on the button does not even appear on android.

```csharp
public Button ElevatedButton(string content)
    => new Button(content)
        .Padding(24)
        .FontSize(14)
        .HeightRequest(40)
        .CornerRadius(20)
        .TextColor(Current.OnBackground)
        .BackgroundColor(Current.Background)
        .Shadow(new Shadow()
            .Brush(Colors.Black)
            .Offset(1,1)
            .Radius(5)
            .Opacity(0.2f))
        .FontAttributes(MauiControls.FontAttributes.Bold);

public Button FAB(string icon)
    => new Button()
        .ImageSource(icon)
        .CornerRadius(16)
        .WidthRequest(56)
        .HeightRequest(56)
        .BackgroundColor(Current.TertiaryContainer)
        .FontAttributes(MauiControls.FontAttributes.Bold);
```

**Comment by adospace** [comment]
Hi, sorry for the late reply, just looking at the code now.
Seems you're setting the Padding to 24 not leaving enough room for the text.
Not sure why iOS is working, much probably in that case such a large value is not honored by the system.

**Comment by cris-m** [comment]
Thanks. That was the issue in android. Actually it was a mistake, `Button` has ` Padding(24, 0)` padding in material design
