### ISSUE TITLE
SfTextInputLayout doesn't render

### ISSUE THREAD

**Issue by Raystorm7** [adospace/reactorui-maui#145]
Hi,
I have tried to use the SfTextInputLayout of Syncfusion components (https://help.syncfusion.com/maui/textinputlayout/getting-started)
but it doesn't render in Reactor MAUI.

I have use this code:

```
[Scaffold(typeof(Syncfusion.Maui.Core.SfView))]
public abstract class SfView { }

[Scaffold(typeof(Syncfusion.Maui.Inputs.SfMaskedEntry))]
public partial class SfMaskedEntry { }

[Scaffold(typeof(Syncfusion.Maui.Core.SfContentView))]
public abstract class SfContentView { }

[Scaffold(typeof(Syncfusion.Maui.Core.SfTextInputLayout))]
public partial class SfTextInputLayout { }
```

And also tried this:

```
[Scaffold(typeof(Syncfusion.Maui.Core.SfTextInputLayout))]
    public partial class SfTextInputLayout
    {
        public SfTextInputLayout Content(Func<VisualNode> render)
        {
            this.Set(Syncfusion.Maui.Core.SfTextInputLayout.ContentProperty,
                new MauiControls.DataTemplate(() => TemplateHost.Create(render()).NativeElement));

            return this;
        }
    }
```

![image](https://github.com/adospace/reactorui-maui/assets/7420345/d0f60cb8-95bd-4093-ac8a-8c12311ec055)

[Here](https://github.com/Raystorm7/SfInputReactorMauiIssue/) a repo.

**Comment by adospace** [comment]
this is an example of how to use the Syncfusion library:
https://github.com/adospace/mauireactor-integration/blob/main/Syncfusion/SfIntApp/Controls/Syncfusion.cs
https://github.com/adospace/mauireactor-integration/blob/main/Syncfusion/SfIntApp/Pages/MainPage.cs

use that repo to ask about problems on third-party control integrations, Thanks
