### ISSUE TITLE
Shell's FlyoutIcon is not displayed, how to solve it?

### ISSUE THREAD

**Issue by ym1100** [adospace/reactorui-maui#159]
I created a navigation mode using Shell's FlyoutItem and set  flyouticon, but the icon did not display. When I changed window size , the icon displayed,

I looked MauiReactor.WeatherTwentyOne samples , it was also the first time it didn't show icon

windows 11,.net7.0-windows10.0.19041.0

**Comment by adospace** [comment]
hum, it appears a standard MAUI issue, can you create a minimal project that reproduces the issue? The problem is visible only in Windows or also in Mac/Android/iOS?

**Comment by ym1100** [comment]
the problem is visible in Windows, android displayed normally, mac/ios not test.
then I use maui xmal layout, Shell's flyouticon can be displayed normally,
![截图_20231004171646](https://github.com/adospace/reactorui-maui/assets/47493444/f4803327-3878-4b02-9df3-1a0d9e17edcc)

**Comment by adospace** [comment]
Seems that I can't reproduce the issue. 

I've created different sample projects published here:
https://github.com/adospace/mauireactor-samples/tree/main/Controls/ShellTestPage
and everything appears working on Windows.

Can you share a minimal reproduction project that shows the problem?

**Comment by ym1100** [comment]
thanks,
I'm using this example, https://github.com/adospace/mauireactor-samples/tree/main/Controls/ShellTestPage
it's no  problem.

us this ,have problem ,icon no display
https://github.com/adospace/reactorui-maui/tree/main/samples/MauiReactor.WeatherTwentyOne
![20231005140106](https://github.com/adospace/reactorui-maui/assets/47493444/1c2679c5-a59d-4d72-a92c-be70d96e4afa)

**Comment by adospace** [comment]
OK, it seems that the custom item template is not working as expected in standard Maui either.

I think I'll wait for the .NET 8 to see if there are any fixes on this thing, in the meanwhile I can suggest just avoiding using the custom item template:

![image](https://github.com/adospace/reactorui-maui/assets/10573253/1a2fcd85-22e5-49f0-b5ba-289eccfc225c)

![image](https://github.com/adospace/reactorui-maui/assets/10573253/da1a2439-54f5-4013-a406-cb2e03930546)
