### ISSUE TITLE
Label takes Height and Width of the Grid container

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#160]
I was creating a outline Text field component like the one below:

<img width="299" alt="Screenshot 2023-10-12 at 17 01 16" src="https://github.com/adospace/reactorui-maui/assets/29815096/8cb780ff-dccb-4bf6-9318-51b35705d151">

Here is the result
<img width="299" alt="Screenshot 2023-10-12 at 17 01 16" src="https://github.com/adospace/reactorui-maui/assets/29815096/104adece-53e4-4e5b-9ff8-afca14d0063e">

When I focus I get this.
<img width="299" alt="Screenshot 2023-10-12 at 17 01 16" src="https://github.com/adospace/reactorui-maui/assets/29815096/f55d8298-7308-4ff1-a01b-7a949fd86896">

But putting the background to the placeholder label, I realized that the label took the width and height of the entire container. Here is the result
<img width="299" alt="Screenshot 2023-10-12 at 17 01 16" src="https://github.com/adospace/reactorui-maui/assets/29815096/46ac7e1d-6eb7-4d45-a4d8-a7bd384b8b27">

Here is the code:
```csharp
    public VisualNode OutlinedTextField(string label, string supportText, Action<string> textChangedAction)
        => Component.Render(context =>
        {
            MauiControls.Entry _entryRef = null;
            var state = context.UseState<(bool IsFocused, bool IsFilled)>();

            return new Grid("* Auto", "*")
            {
                    new Grid("*", "*")
                    {
                        new Border
                        {
                            new Grid 
                            {
                                new BorderlessEntry(entryRef => _entryRef = entryRef)
                                .OnFocused(() => state.Set(s => (IsFocused: true, s.IsFilled)))
                                .OnUnfocused(() => state.Set(s => (IsFocused: false, s.IsFilled)))
                                .OnAfterTextChanged(text =>
                                {
                                    state.Set(s => (s.IsFocused, IsFilled: !string.IsNullOrWhiteSpace(text)));
                                    textChangedAction?.Invoke(text);
                                }),
                            }
                        }
                        .Padding(16,0)
                        .StrokeThickness(2)
                        .Stroke(Colors.Black),
                        new Label(label)
                            .Padding(16,0)
                            .TextColor(Colors.Black)
                            .VerticalTextAlignment(TextAlignment.Center)
                            .BackgroundColor(Colors.White)
                            .FontSize(state.Value.IsFocused || state.Value.IsFilled ? 12 : 16)
                            .TranslationY(state.Value.IsFocused || state.Value.IsFilled ? -25 : 0)
                    }
                    .Padding(0)
                    .HeightRequest(56)
                    ,

                    Current.BodySmall(supportText)
                        .Padding(16, 4, 16, 0)
                        .GridRow(1)
                        .TextColor(Current.Error) 
            }
            .OnTapped(()=>_entryRef?.Focus());
        });
```

**Comment by adospace** [comment]
I'm not sure which issue you're reporting about MauiReactor, if the problem is the label is not completely visible, I think you have to play a bit with the translation value:

`.TranslationY(state.Value.IsFocused || state.Value.IsFilled ? -25 : 0)`

maybe something like -32 or so could do the trick

**Comment by cris-m** [comment]
Thanks for the help. `TranslationY` is not the problem. the problem is that the `Label` takes the same height and width of it contains. When I apply `TranslationY` it moves with it width and heigh.  if I change the background of the `BorderlessEntry` to red and background of the `Label` to blue. get the following

- unfocused 
The whole Text field is now blue
![Screenshot_20231012-1943032](https://github.com/adospace/reactorui-maui/assets/29815096/5a46ce2c-ec60-4d8b-9fda-25820892f42c)

- focused
The label translate to -25. Now the `BorderlessEntry` entry with red background appear. The blue part is the `Label` it has the same size as the `BorderlessEntry`
![Screenshot_20231012-1942572](https://github.com/adospace/reactorui-maui/assets/29815096/112d9b1a-e254-458f-9060-05d99b5a4477)

**Comment by adospace** [comment]
The label occupies all the available space that is that provided by the parent grid, try to put VCenter() on the label

**Comment by cris-m** [comment]
Yeah, `VCenter()` fix the height issue. The width is the same width as the container
- Unfocused 
![Screenshot_20231012-2023112](https://github.com/adospace/reactorui-maui/assets/29815096/9f37a53a-6986-47dd-9658-220533558c77)

- Focused
![Screenshot_20231012-2023202](https://github.com/adospace/reactorui-maui/assets/29815096/f3eb7386-d979-46a9-831d-6f7c8f630976)

**Comment by juanyacovino77** [comment]
Try with HCenter() for the width
