### ISSUE TITLE
Memory Consumption of SetState

### ISSUE THREAD

**Issue by salty-flower** [adospace/reactorui-maui#161]
Hi there, first of all THANK YOU @adospace for creating this awesome library! It is such a breeze to me compared to traditional XAML and `BindableProperty` kind of data binding.

I was doing a component where it'll displays data from remote. To keep it up to date I have a background task. So it looks like:
```csharp
private async Task RefreshDataInBackground(CancellationToken token)
{
    while (!token.IsCancellationRequested)
    {
        await Task.Delay(REFRESH_INTERVAL * 1000, token);
        var items = await FetchAsync(_id);
        SetState(s => s.Items = items);
    }
}
```
and it creates this task when user clicks on a button, where the `OnTapped` is
```csharp
private async Task LoadAsync()
{
   if (State.Expanded)
   {
       _tokenSource.Cancel();
       SetState(s => s.Expanded = false);
       return;
   }

   // initial loading
   var items = await FetchAsync(_id);

   if (ae.Count > 0)
       SetState(s =>
       {
           s.Expanded = true;
           s.Items = items;
       });

   // Start the background refresh task
   _tokenSource = new CancellationTokenSource();
   _refreshTask = RefreshDataInBackground(_tokenSource.Token);
}
```
Finally I'm attempting to destroy the task with
```csharp
protected override void OnWillUnmount()
{
    _tokenSource.Cancel();
    GC.Collect();
    base.OnWillUnmount();
}
```

It works well until today I play with it by setting `REFRESH_INTERVAL` to `1`, i.e. every one second. Then the memory taken grows insanely - every refresh takes extra 7MB. When I comment out the `SetState(s => s.Items = items);`, the memory footprint remains still.
![VS Screenshot](https://github.com/adospace/reactorui-maui/assets/95509524/a931a9db-86b7-4b3b-bf64-a55b99362f6e)

I guess part of the issue can be my integrating Components with XAML via `ComponentHost`, so component unmounting might be problematic.

**Comment by salty-flower** [comment]
I built the application without XAML this time. By putting breakpoints I see parent's `OnWillUnmount()` is called but not for children components (inside a `ListView` from parent `Render()`). I guess there shouldn't be recycling of children since `Render()` creates new instances of children components every time? But the memory consumption remained high after parent is unmounted😢

**Comment by juanyacovino77** [comment]
I think infinite loops are going on here.

- Why do you call SetState() inside the while loop? You are replacing the entire s.Items list every time the while loop so every time SetState() is called the components got re-rendered.... it may help you using invalidateComponent param at SetState to not re-render if you dont need it.  Anyway a SetState called inside a while loop i dont believe is is a good idea.

- It would be better to subscribe for  new items event inside the OnMounted() life cycle method of the component, so when you notice new items you invoke a event  from the background task and gets catched inside the component method. 

- showing the entire component code may us help you

**Comment by salty-flower** [comment]
Yeah, indeed I put an infinite loop, as you see. It fetches data and updates state, then sleeps until next iteration.
- You are right that I'm lazy there to replace the whole list... I was thinking once the old state is not needed, GC will clean it up automatically.
- That's definitely possible, but looks like it's using mechanisms other than state itself? Is this encouraged though?
- My component is bit integrated thus it can be bit cumbersome. I'll come up with a minimal reproducible example and post later.

This issue is not likely to be critical in production since the update interval will be around 1 minute then. However I feel the fundamental issue is what prevents GC from cleaning stuff up. Maybe I can take a deeper look at this library and see whether it keeps reference to old components / states (most possible way to prevent GC IMHO).

**Comment by adospace** [comment]
Yes, the problem is the loop inside your component. Calling SetState creates a new render tree at each loop, but GC can't reclaim the old component because it contains the still-running loop.
You should create a service instead.
In pseudo-code:

```csharp
class FetchService
{
    public event EventHandler<EventArgsWithItems>? NewItemsArrived;
    
    public void Start()
    {
    _tokenSource = new CancellationTokenSource();
    Task.Run(RefreshDataInBackground, _tokenSource.Token);
    }
    
    public void Stop()
    {
    _tokenSource.Cancel();
    }
     
    
    private async Task RefreshDataInBackground(CancellationToken token)
    {
      try
      {
          while (!token.IsCancellationRequested)
          {
              var items = await FetchAsync(_id);
    
              NewItemsArrived?.Invoke(this, new EventArgsWithItems(items));
    
              await Task.Delay(REFRESH_INTERVAL * 1000, token);
          }
      }
      catch (CancellationTokenException)
      {
      
      }
    }
}
```

register the service in the program.cs:

` builder.Services.AddSingleton<FetchService>();`

and inject in the component:

```csharp
void OnMount()
{
    var fetchService = Services.GetRequiredService<FetchService>();
    FetchService.NewItemsArrived += OnNewItemsArrived;

   //Start/Stop service on IsExpanded event in the Render function...
}

void OnWillUnmount()
{
    var fetchService = Services.GetRequiredService<FetchService>();
    FetchService.NewItemsArrived -= OnNewItemsArrived;
}



void OnNewItemsArrived(object sender, EventArgsWithItems args)
{
    //TODO: use an observable collection and only add new items/remove old ones
    //https://adospace.gitbook.io/mauireactor/components/controls/collectionview/interactions
    SetItems(s => s.Items = args.Items);
}
```

Here are a few other hints:
1) Put the service class in a separate assembly/project otherwise hot-reload won't work
2) Use an ObservableCollecrtion instead (https://adospace.gitbook.io/mauireactor/components/controls/collectionview/interactions): this will avoid recreating the component and CollectionView would be much more efficient in memory consumption
3) Use a WebSocket to receive new items instead of polling the server which could overflood the back-end. Take a look a this project: https://github.com/adospace/mauireactor-samples/tree/main/ChateoApp

**Comment by salty-flower** [comment]
> Calling SetState creates a new render tree at each loop, but GC can't reclaim the old component because it contains the still-running loop.

This explains everything, thanks a lot! I appreciate your efforts in writing pseudo code and it's really clear. I'll create a separate service with observable collection to handle this. However since I'm relying on external backend currently so I can't adopt WebSocket😂.

It seems I haven't gone through the docs carefully enough. However when I search for keyword "memory" I didn't get any results (well one actually, but it was about hot reload).

BTW, if you think it'll be a good idea to mention this as an anti-pattern under [Does this support ObservableCollection for CollectionView?](https://adospace.gitbook.io/mauireactor/q-and-a/does-this-support-observablecollection-for-collectionview), I'd be happy to draft something and open a PR. Thanks!
