### ISSUE TITLE
Is it possible to use Behavior?

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#169]
I would like to know if there is a ways to use `Behavior`. Like to change color of `svg` image using `IconTintColorBehavior`  of `.NET MAUI Community Toolkit`

_Originally posted by @cris-m in https://github.com/adospace/reactorui-maui/issues/14#issuecomment-1793655239_

**Comment by adospace** [comment]
https://adospace.gitbook.io/mauireactor/deep-dives/behaviors
