### ISSUE TITLE
How to play mp3 sound with MauiReactor?

### ISSUE THREAD

**Issue by juanyacovino77** [adospace/reactorui-maui#171]
How can we play a simple mp3 wav - ringtone sound on certain actions at MauiReactor apps?

I have succesfully scaffolded the MediaElement of .NET MAUI and it is barely working but I think I need something simpler than a hole media player

**Comment by adospace** [comment]
Sorry but how does this question relate to MauiReactor? I don't know what the options are to play sounds with MAUI but whatever should work the same in MauiReactor.

Why is MediaElement barely working?

**Comment by adospace** [comment]
this can work-> https://www.andreasnesheim.no/playing-audio-in-a-net-maui-app/ ?

```csharp
private async void OnCounterClicked()
{
    var audioPlayer = AudioManager.Current.CreatePlayer(await FileSystem.OpenAppPackageFileAsync("ukelele.mp3"));

    audioPlayer.Play();
}
```
