### ISSUE TITLE
Seperate Solution file for Samples

### ISSUE THREAD

**Issue by agwanyaseen** [adospace/reactorui-maui#172]
Currently to open sample we have to use **MauiReactor.sln** which also opens framework related code, which I think is a bad design. 
We can create a new sln file named "**MauiReactorSample.sln**" inside Samples folder. If this is approved I can take this ahead.

Thank You

**Comment by adospace** [comment]
Hi, the samples included in this solution are primarily used to test framework features thus they have direct references to the MauiReactor project.
If you put those projects inside another solution you'll end up referencing the MauiReactor NuGet package or fall back by adding MauiReactor project to the Samples solution.

Another repo exists that contains many other sample apps and a solution showing all the MauiReactor features:
https://github.com/adospace/mauireactor-samples

Probably we need a Gallery/Showcase app (that could be also published to the stores) that shows MauiReactor features including source code.

**Comment by agwanyaseen** [comment]
This sounds reasonable to not create Another Solution file for Samples.
Thanks for [sample](https://github.com/adospace/mauireactor-samples) I was not aware of this repo.

Bdw you are doing a great work @adospace
