### ISSUE TITLE
Hi @adospace is .net 8.0 working fine for you?

### ISSUE THREAD

**Issue by adospace** [adospace/reactorui-maui#176]
Hi @adospace is .net 8.0 working fine for you?

I upgraded my working .net 7.0 project to .net 8.0 by making the following changes:

- `<TargetFrameworks>net8.0-ios;net8.0-android</TargetFrameworks>`
- Add the following two packages:
```
<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
```
- Downloaded this repo, switched to the net-8-rc2 branch
- Commented out `<PackageReference Include="Reactor.Maui" Version="1.0.148" />` and added project reference to:
```
  <ItemGroup>
    <ProjectReference Include="..\reactorui-maui\src\MauiReactor\MauiReactor.csproj" />
  </ItemGroup>
```

When I build and run the solution, the app launches in iOS Simulator but when I click on a button the event doesn't fire. This works fine on .net 7.0.

Thanks!

_Originally posted by @Code-DJ in https://github.com/adospace/reactorui-maui/issues/166#issuecomment-1811361507_

**Comment by adospace** [comment]
I've made many tests under iOS too, and seems that everything is working fine for me.
BTW MauiReactor package updated to .net 8 will be out as soon as AppVeyor will be capable of building .net 8 assemblies, hopefully soon.

**Comment by Code-DJ** [comment]
> I've made many tests under iOS too, and seems that everything is working fine for me. BTW MauiReactor package updated to .net 8 will be out as soon as AppVeyor will be capable of building .net 8 assemblies, hopefully soon.

Thank you for testing, not sure why the project doesn't work. I will start a new project and copy over the code few files at a time after new packages are out 🙏🏼.

**Comment by adospace** [comment]
If you run the test app from the net-8-rc-2 branch, is it working for you?

**Comment by Code-DJ** [comment]
> If you run the test app from the net-8-rc-2 branch, is it working for you?

Yes, the MauiReactor.TestApp works fine, so something in my app that .net 8 doesn't like.

**Comment by Code-DJ** [comment]
@adospace looks like the build-deploy is not working. See https://github.com/vers-one/EpubReader/blob/master/.github/workflows/update-versions.yml

There they use `file` instead of `files`. Also, looks like if you put the list on a separate line you need to use `|`.

**Comment by adospace** [comment]
yes trying to setup github actions as an alternative

**Comment by Code-DJ** [comment]
Hi @adospace I figured the issue - `OnTapped` does not work on .net 8.

Changed this:
```
new Button("Foo")
    .OnTapped(() => MyAction())
```

to:
```
new Button("Foo", () => MyAction())
```

It works.

**Comment by adospace** [comment]
Hum, interesting, actually button have the OnClicked event, probably net 8 now swallow the tapped event for buttons and that makes sense to me
