### ISSUE TITLE
Is it possible to create properties for inline components?

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#178]
I had an Inline Components, I would like to create some property. I would like to use property since the component will render different UI based on result from web request every  10 minutes
```csharp
public VisualNode Card(string title)
        => Component.Render(context =>
        {
        
        });
```

**Comment by adospace** [comment]
You can pass your properties as parameters to the method that creates the inline component no? Like the title parameter in you sample code

**Comment by cris-m** [comment]
Yes I can do that. But can that property update a state change if it value change?

**Comment by adospace** [comment]
You have to re-render the component every 10 minutes passing a different property value
