### ISSUE TITLE
is BindableLayout supported?

### ISSUE THREAD

**Issue by nor0x** [adospace/reactorui-maui#181]
I was wondering how I could port the following MAUI XAML code to reactorui-maui (which is an awesome piece of software, thank you so much for building it 👏)

```
<StackLayout
        Orientation="Horizontal"
        BindableLayout.ItemsSource="{Binding MyItems}">
    <BindableLayout.ItemTemplate>
        <DataTemplate>
        ...
        </DataTemplate>
    </BindableLayout.ItemTemplate>
</StackLayout>
```

`BindableLayout` is helpful for `Layout` derivatives to render children bound to an `ItemsSource`. Unfortunately I was not able to find some information about the support for BindableLayout in the docs or in the source of this repository.

**Comment by adospace** [comment]
Hi, yes you "could" use BindableLayout in MauiReactor too but you won't find any documentation on that because actually in MVU things are much easier:

```csharp
new HStack
{
    State.MyItems.Select(RenderItem)
}


VisualNode RenderItem(Item item)
   => new Label(item.Name);
```

**Comment by nor0x** [comment]
of course, that make sense! thank you 😄
