### ISSUE TITLE
How to focus Entry control?

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#184]
I have see the only way to focus `Entry` control in dotnet maui is to use [`SetFocusOnEntryCompletedBehavior`](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/behaviors/set-focus-when-entry-completed-behavior.md).  But `SetFocusOnEntryCompletedBehavior` just enable the developer to focus the next element. I would like to know if there is a way to focus an entry when `render` message execute. Scenario like when open the `OTP` page of an app, the first entry is focus in order for the numeric keyboard to be visible.

**Comment by adospace** [comment]
this can work?
https://github.com/adospace/reactorui-maui/blob/main/samples/MauiReactor.TestApp/Pages/ElementRefPage.cs
