### ISSUE TITLE
Unable to set ToolTipProperties on button control

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#197]
I was trying to set a `ToolTipProperties`on button using `Set` (use to set a specific dependency property of the native control).

```csharp
 new Button("text")
      .Set(MauiControls.ToolTipProperties.TextProperty, "Test"),
```

**Comment by cris-m** [comment]
I have test it in normal MAUI app and it work perfectly.

**Comment by adospace** [comment]
may I ask the the version of MauiReactor and the system you're testing? windows or Mac?

**Comment by cris-m** [comment]
I am testing on Mac and the `MauiReactor` version is `2.0.7-beta`

**Comment by cris-m** [comment]
updating `Reactor.Maui` and `Reactor.Maui.Canvas` throw an error when using inline component on `Component.Render`:
example:
```csharp
 public VisualNode OutlinedTextField(string label, string supportText)
  => Component.Render(context =>
  {
  }
```
I get the following error:
` error CS0411: The type arguments for method 'Component.Render<S>(Func<ComponentContextState<S>, VisualNode>, S?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

**Comment by adospace** [comment]
Yes you have to specify the type of the state, for example Render<double>(...) or Render<(double param1, int param2)>(...)

**Comment by cris-m** [comment]
I got an other issue which is unrelated.  The simulator cannot start the app.
```
Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:10000: Connection refused
```
I will close this issue because I was unable to test.
