### ISSUE TITLE
Unable to use HotReload with different assembly

### ISSUE THREAD

**Issue by alex-relov** [adospace/reactorui-maui#205]
Hello! I have a problem with hot reload. I have two assembly: TimeTracker.Core contain extension method `RegisterDal` and TimeTracker.Reactor contain ui layer. In `MauiProgram` I register: `builder.Services.RegisterDal();`
 Next:
1. Run app in debug mode in iOS simulator
2. Start  hot reload `dotnet maui-reactor -f net8.0-ios`
3. Make change in Page and save

```
alex@alexs-MacBook-Air TimeTracker.Reactor % dotnet maui-reactor -f net8.0-ios
MauiReactor Hot-Reload CLI
Version 2.0.24.0
Press Ctrl+C or Ctrl+Break to quit
Setting up build pipeline for TimeTracker.Reactor project...done.
Monitoring folder '/Users/alex/source/TimeTracker/TimeTracker.Reactor'...
Detected changes to 'Pages/Projects/ProjectsPage.cs'
Replacing syntax tree for: Pages/Projects/ProjectsPage.cs
/Users/alex/source/TimeTracker/TimeTracker.Reactor/MauiProgram.cs(33,9): error CS1929: 'IServiceCollection' does not contain a definition for 'RegisterDal' and the best extension method overload 'DalExtensions.RegisterDal(IServiceCollection)' requires a receiver of type 'IServiceCollection'
```

**Comment by adospace** [comment]
In this case, you have to use the full mode:
dotnet-maui-reactor -f [net8.0-android|net8.0-ios|net8.0-maccatalyst|windows10.0.19041.0] --mode Full
