### ISSUE TITLE
What is the 'OnTapped Method' difference?

### ISSUE THREAD

**Issue by lukewire129** [adospace/reactorui-maui#206]
![image](https://github.com/adospace/reactorui-maui/assets/54387261/b58d3969-e0ff-4c3c-a233-38327ddcc8a1)

**Grid** Available
**CollectionView** Unavailable

I've followed the reference, but I'm using the same 'CellExtensions', but I'm not seeing the
Why is this happening?

**EmptyItemArea Method**
```
void EmptyItemArea(bool isItem = false)
{

}
```

**Comment by adospace** [comment]
OnTapped is an event, you should pass a callback like `.OnTapped(()=>...)` or `.OnTapped(MyMethod)`

**Comment by adospace** [comment]
do you mean the arguments of the OnTapped event? if so any event in MauiReactor allows you to access event args using code like this:

`.OnTapped((s, e)=> e. is of type TappedEventArgs)`

or 

```csharp
.OnTapped(MyEvent)

void MyEvent(object? sender, TappedEventArgs args)
{
...
}

```

**Comment by lukewire129** [comment]
Ahhh! 
I thought I understood OnTapped as follows.
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/tap?view=net-maui-8.0

I was asking if it would be possible to customize it to be similar to Command and CommandParameter :)

**Comment by adospace** [comment]
Ok, I see now what you mean. To fully customize the tapo gesture you have to create a TapGestureRecognizer like the following:

```csharp
CollectionView(
    TapGestureRecognizer()
        .Buttons(MauiControls.ButtonsMask.Secondary)
        .NumberOfTapsRequired(2)
        .OnTapped(()=>...)
    )
    .ItemsSource(ItemsSource, RenderItem)
```

In the future, please provide a more descriptive explanation of your issues

**Comment by lukewire129** [comment]
Thank you :)
