### ISSUE TITLE
How to use IgnoreSafeArea and SetUseSafeArea in iOS?

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#212]
I would like to know how to use `SetUseSafeArea` on `ContentPage` or `IgnoreSafeArea` on layout like `Grid`,...

**Comment by adospace** [comment]
Please be more detailed in your question and how it's related to MauiReactor

**Comment by cris-m** [comment]
I am try to use SetUseSafeArea or IgnoreSafeArea in maui reactor component. I don't know how to do it. I was reading about it on Microsoft documentation
https://learn.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout

```xml
<ContentPage 
     xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
     Title="Safe Area"
     ios:Page.UseSafeArea="true">
    <StackLayout>
        
    </StackLayout>
</ContentPage>
```

or 

```csharp
On<iOS>().SetUseSafeArea(true);
```

I want to know how to achieve this in  `MauiReactor`

**Comment by cris-m** [comment]
This fix the issue about iOS `UseSafeAreaProperty` but I am unable to use `IgnoreSafeArea` on layout like `Grid` or `StackLayout`.

According to Microsoft documentation:
> The [Layout](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.layout) class defines a [IgnoreSafeArea](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.layout.ignoresafearea#microsoft-maui-controls-layout-ignoresafearea) property that ensures that content is positioned on an area of the screen that is safe for all iOS devices. This property can be set to true on any layout class, such as a [Grid](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.grid) or [StackLayout](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.stacklayout), to perform the equivalent of this platform-specific.

how to use the `IgnoreSafeArea` on the `Grid` inside the `ContentPage`?

```csharp
return ContentPage(
             Grid(
            )
        )
        .OnAppearing(OnCalcSafeAreaSize)
        .OniOS(_ => _
            .Set(MauiControls.PlatformConfiguration.iOSSpecific.Page.UseSafeAreaProperty, false));
```

**Comment by adospace** [comment]
Hi, unfortunately, IgnoreSafeArea is not a dependency property so for now you have to set explicitly:

```c#
            Grid(gridRef => 
            {
                if (gridRef != null)
                    gridRef.IgnoreSafeArea = true;
            })

```

in future version I'll integrate it in MauiReactor so you'll be able to write something like:

`Grid().IgnoreSafeArea(true)`
