### ISSUE TITLE
Is it possible to make HotReload work while using DI?

### ISSUE THREAD

**Issue by nomurayoshuak** [adospace/reactorui-maui#213]
@adospace 
I am referring to the Clean Architecture in my project, where I separate the database read/write components and the WebAPI invocation parts by using interfaces and implementations. At that time, I encountered difficulty as HotReload does not function when using a DI container. I found this information in the documentation, stating that HotReload does not work when using DI. https://adospace.gitbook.io/mauireactor/deep-dives/dependency-injection

Is it possible to make HotReload work while using DI? I'm unsure how to implement it in a separate assembly, and I would greatly appreciate it if you could provide an example of defining interfaces in the app project and implementing those interfaces in a separate project (assembly).

Below is the configuration of my project.

```c#
interface IUserAuthService
{
    event EventHandler<bool> UserAuthChanged;

    bool IsAuthed();
    Task<bool> LoginWithEmail(string email, string password);
    Task<bool> LoginWithPhoneNumber(string phoneNumber, string password);
    Task<bool> Logout();
}
```

```c#
class UserAuthService : IUserAuthService
{
  // ...
}
```

```c#
// MauiProgram.cs
builder.Services.AddSingleton<IUserAuthService, UserAuthService>();
```

```c#
partial class LoginPage : Component<LoginPageState>
{
    [Inject]
    IUserAuthService _userAuthService;

  // ...
}
```

**Comment by adospace** [comment]
Hi, you need to create a new project, class library, in Visual Studio (or vs code, rider etc) and reference it from the main MAUI project.
Then move all the services and models inside that project: after that hot-reload should work.

**Comment by adospace** [comment]
for example:
https://github.com/adospace/kee-mind/tree/main/src
