### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by dialtonetech** [adospace/reactorui-maui#226]
HI Well done on a really cool and useful library.

You mention Figma to Reactorui-maui, can't seem to see the code generation, is their an example.

Thank you in advance

**Comment by adospace** [comment]
Figma to MauiReactor tool isn't something I'm investing time to develop for now.
While working on that I found that even if the tool is somewhat useful, the resulting c# code is far from being "perfect": you still have to deeply modify and correct it losing the benefits of the generation.
Furthermore, I found generally lack of interest in the community for tools like that so I decided to pause the development.

**Comment by dialtonetech** [comment]
I am happy to invest time and effort into it
