### ISSUE TITLE
Integrating Mapsui for OSM with .NET MauiReactor: Challenges and Errors

### ISSUE THREAD

**Issue by DeyvidyBraz** [adospace/reactorui-maui#227]
I am attempting to integrate Mapsui mapping functionalities, specifically for OpenStreetMap (OSM), into a .NET MAUI project with the aid of MauiReactor. Despite several attempts, I have faced challenges that I have not been able to overcome.

The main difficulty arises in integrating the Mapsui map component into the UI managed by MauiReactor. One of the attempts included defining a custom MapControl component using the [Scaffold(typeof(Mapsui.UI.Maui.MapControl))] attribute, trying to configure it to display an OSM map. Here's an example of the code used:

```
[Scaffold(typeof(Mapsui.UI.Maui.MapControl))]
partial class MapControl { }

public override VisualNode Render()
{
    return ContentPage(
        new MapControl()
            .Map(map =>
            {
                map.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
                return map;
            })
    );
}
```

When attempting to compile, I encountered the following error:

"Cannot convert lambda expression to type 'Map' because it is not a delegate type".

Has anyone successfully implemented Mapsui to use OSM maps within a .NET MAUI project with MauiReactor, and can offer any guidance or example on how to overcome this issue?
Are there any tips, solutions, or best practices for integrating Mapsui with .NET MAUI and MauiReactor, especially for using OpenStreetMap maps?
Any help, suggestions, or direction would be immensely valuable. I am excited to make this integration work and to explore the combined potential of these technologies in my application.

Thank you in advance for your support and any assistance you can provide.

**Comment by adospace** [comment]
Hi, yes, integrating third-party controls is a pain point of MauiReactor, especially for complex controls like Mapsui, let me look at it and I'll let you know ASAP.

For further reference this is the integration of Google Maps (easier than Mapsui I guess):

https://github.com/adospace/reactorui-maui/tree/main/samples/MauiReactor.MapsDemo
https://github.com/adospace/reactorui-maui/tree/main/src/MauiReactor.Maps

**Comment by DeyvidyBraz** [comment]
.NET MAUI version: 8.0.14
MauiReactor version: 2.0.34
Mapsui version: 5.0.0-beta.1


Hello,

Thank you very much for your quick response and for looking into the issue with integrating third-party controls like Mapsui into MauiReactor projects. I truly appreciate your willingness to help and am looking forward to any guidance or solutions you might find.

I'm aware of the Google Maps integration example provided in the reactorui-maui samples and understand that it might be simpler compared to what I'm trying to achieve with Mapsui and OpenStreetMap. Although the Google Maps integration serves as a great reference, there is a specific requirement in my project that necessitates the use of Mapsui for accessing OSM (OpenStreetMaps) data. This requirement is primarily due to the open-source nature of OSM and its compatibility with our project's goals.

In the meantime, I'll continue to experiment and try different approaches to integrate Mapsui with MauiReactor. Should I make any progress or come across a viable solution, I'll be sure to report back and share my findings with the community.

Again, thank you for your support and for the invaluable resources you've provided. Your assistance is greatly appreciated, and I'm hopeful that with your guidance, we can find a way to successfully integrate Mapsui into the MauiReactor framework.

**Comment by adospace** [comment]
Are you able to make it work on a standard MAUI application?
following this guide 
https://mapsui.com/documentation/getting-started-maui.html
seems it doesn't even start for me on android emulator API 34

**Comment by adospace** [comment]
this is how you can integrate the Mapsui:

```c#
class MainPageState
{
    public Map? Map {  get; set; } 
}

class MainPage : Component<MainPageState>
{
    protected override void OnMounted()
    {
        State.Map = new Map();
        State.Map.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());

        base.OnMounted();
    }

    public override VisualNode Render()
        => ContentPage(
            Grid(
                new MapControl()
                    .Map(State.Map)
            )                
        );
}
```

Be careful to put the Map in the state so that you create it only once on the OnMounted().

MapControl is scaffolded as usual:

```c#
[Scaffold(typeof(Mapsui.UI.Maui.MapControl))]
partial class MapControl
{
}

```

NOTE: Tested with Windows platform, Android seems not working (I guess it's something they'll fix before production release)

**Comment by DeyvidyBraz** [comment]
Actually, I haven't tried running it on the Android emulator with API 34; my tests were conducted with API 33. I was able to run it successfully by strictly following the documentation provided for setting up a basic .NET MAUI application with Mapsui.

Here's the core implementation I used based on the documentation:

In the MainPage.xaml.cs:

```
public MainPage()
{
    InitializeComponent();
    var mapControl = new Mapsui.UI.Maui.MapControl();
    mapControl.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
    Content = mapControl;
}
```
And in the MainPage.xaml:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="testeMapsui.MainPage">

</ContentPage>
```
This setup worked for me when using the Genymotion emulator (it also worked on physical devices). It's possible that the emulator type might influence the outcome, as suggested.

**Comment by DeyvidyBraz** [comment]
> é assim que você pode integrar o Mapsui:
> 
> ```cs
> class MainPageState
> {
>     public Map? Map {  get; set; } 
> }
> 
> class MainPage : Component<MainPageState>
> {
>     protected override void OnMounted()
>     {
>         State.Map = new Map();
>         State.Map.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
> 
>         base.OnMounted();
>     }
> 
>     public override VisualNode Render()
>         => ContentPage(
>             Grid(
>                 new MapControl()
>                     .Map(State.Map)
>             )                
>         );
> }
> ```
> 
> Tenha o cuidado de colocar o Mapa no estado para que você o crie apenas uma vez no OnMounted().
> 
> MapControl é estruturado como de costume:
> 
> ```cs
> [Scaffold(typeof(Mapsui.UI.Maui.MapControl))]
> partial class MapControl
> {
> }
> ```
> 
> NOTA: Testado com plataforma Windows, o Android parece não funcionar (acho que é algo que eles consertarão antes do lançamento da produção)

Thanks, I'll test it right away

**Comment by DeyvidyBraz** [comment]
Thank you so much for your help! Your advice worked perfectly, and I managed to get everything up and running. It really made a difference, and I can’t tell you how much I appreciate it.

Thanks a bunch for taking the time to help me out. You’ve really saved the day!
