### ISSUE TITLE
Xaml integration State Of Component not Update the UI using BottomSheet

### ISSUE THREAD

**Issue by Ali1Jamal** [adospace/reactorui-maui#235]
i just try to warp this lib  [The49.Maui.BottomSheet](https://github.com/the49ltd/The49.Maui.BottomSheet) but I cant because the page need to inherit BottomSheet and to create a page using MauiReactor I need to inherit Component class so I cant inherit two classes (BottomSheet, Component),
so i decide to create the BottomSheetPage using xaml and the content of the page will be the Maui Reactor Component using xaml integration,  its work but the state didn't update the ui ,for ex when click on Increment button using Counter Component the state of the Counter didn't change. 

here is my Counter Component:
```
class CounterPageState
{
    public int Counter { get; set; }
}

class CounterPage : Component<CounterPageState>
{
    public override VisualNode Render()
        => VStack(spacing: 10, 
            Label($"Counter: {State.Counter}").Center(),
                Button("Click To Increment", () =>
                    SetState(s => s.Counter++))
            ).Center();
}
```

**Screenshots**
![telegram-cloud-photo-size-2-5298940421864544394-y](https://github.com/adospace/reactorui-maui/assets/40013555/71fa1ba8-c7f2-4bf0-bf05-b887c469659e)

**Smartphone :**
 - Device: Realme 7
 -OS: I Only Test On Android

**Comment by adospace** [comment]
have you looked at this?
https://github.com/adospace/mauireactor-integration/tree/main/The49

**Comment by Ali1Jamal** [comment]
I don't know about mauireactor-integration before, The49 definitely works I test it with Counter and the state just works normally, also  mauireactor-integration have nice integrations with other libs that will help me to understand how to warp almost any lib in the Future, thank you very much.
