### ISSUE TITLE
AppShell Template Error

### ISSUE THREAD

**Issue by dialtonetech** [adospace/reactorui-maui#236]
**Describe the bug**
When using the template to create app shell their is a coma 

ScrollView(
    VStack(
        Label("Other Page")
            .FontSize(32)
            .HCenter(), <------- Error remove comma
    )
    .VCenter()
    .Spacing(25)
    .Padding(30, 0)
)

**To Reproduce**
dotnet new maui-reactor-appshell -o my-new-project

**Comment by adospace** [comment]
Thanks for the report I'll fix it in next release
