### ISSUE TITLE
How to use CommunityToolkit IPopupService?

### ISSUE THREAD

**Issue by cris-m** [adospace/reactorui-maui#237]
I was try to use `IPopupService` to create a utility class that manage `Popup` show and dismiss. I want to trigger `Popup` with any visual element pass in it. An example like the [BottomSheetManager](https://github.com/adospace/mauireactor-integration/tree/main/The49) but for `Popup`

**Comment by adospace** [comment]
doesn't this work for you?
https://github.com/adospace/reactorui-maui/blob/main/samples/MauiReactor.TestApp/Pages/ShowPopupTestPage.cs

**Comment by cris-m** [comment]
This one will work. thanks for the help
