### ISSUE TITLE
Debug is not working [global::System.Diagnostics.Debugger.Break();] [Windows Machine]

### ISSUE THREAD

**Issue by itschnie** [adospace/reactorui-maui#238]
**Describe the bug**
It happens quite often that I am not shown the exact errors, but only that there was a stop. This opens the file: "App.g.i.cs" and jumps to line 74 "global::System.Diagnostics.Debugger.Break();"

![grafik](https://github.com/adospace/reactorui-maui/assets/73386340/24e48a6c-b1a3-4b04-af25-ec84f79b33e6)

This makes debugging the error very difficult, as I cannot understand why the error occurs
The Visual Studio IDE itself does not show any errors "No Problems found".

**To Reproduce**
1. Open Visual Studio 2022
2. Trying to Open an App in Debug-Mode
3. It breaks at some point, don't know, why.

**Screenshots**

![grafik](https://github.com/adospace/reactorui-maui/assets/73386340/f6133929-11c2-4782-a8a8-8077571ef27f)
![grafik](https://github.com/adospace/reactorui-maui/assets/73386340/7d9e2cca-c4ad-45f8-b744-75fe29de4658)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by itschnie** [comment]
> I think the problem is not related to MauiReactor but to WinUI. Does it happen with a normal XAML-based MAUI app? Would you happen to have a small repro solution that I can run?

I'll set this up tomorrow because I have to go to work right away :) Thanks for the feedback

**Comment by itschnie** [comment]
What i did:
- Open a Fresh MauiRector-Template
- on MainPage.cs:

[MainPage.cs.txt](https://github.com/adospace/reactorui-maui/files/15209478/MainPage.cs.txt)

that's all :)

https://github.com/adospace/reactorui-maui/assets/73386340/c759a812-d428-41d9-9539-1b184fcc199c

**Comment by adospace** [comment]
You're adding a Page (FooterPage) inside a Grid, furthermore you're creating a Label inside a CanvasView.

A couple of things:
1) Please ensure you understand how a MAUI application works following the MS documentation: https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui?view=net-maui-8.0
2) MauiReactor has a documentation web site too that shows how to create an application : https://adospace.gitbook.io/mauireactor
3) MauiReactor CanvasView is a somewhat advanced concept that requires Skia, please read documentation here: 
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/graphicsview?view=net-maui-8.0
https://adospace.gitbook.io/mauireactor/components/graphics
