### ISSUE TITLE
Large Page Titles on iOS

### ISSUE THREAD

**Issue by mario-zelger** [adospace/reactorui-maui#246]
Hi there

I'm trying to get the iOS-specific large page titles to work while using the `Shell`. [Microsofts documentation](https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-large-title?view=net-maui-8.0) mentions modifying either `PrefersLargeTitles` or `SetLargeTitleDisplay` on the `NavigationPage` or `ContentPage` respectively.

```csharp
var navigationPage = new Microsoft.Maui.Controls.NavigationPage(new iOSLargeTitlePageCode());
navigationPage.On<iOS>().SetPrefersLargeTitles(true);
```
```csharp
using Microsoft.Maui.Controls.PlatformConfiguration;
using Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;
...

public class iOSLargeTitlePageCode : ContentPage
{
    public iOSLargeTitlePageCode
    {
        On<iOS>().SetLargeTitleDisplay(LargeTitleDisplayMode.Never);
    }
    ...
}
```

I either want to to set the `PrefersLargeTitles` or `LargeTitleDisplayMode` option globally. I couldn't get it to work with Reactor and didn't find any information in the documentation regarding this. Maybe you can help me out here? 😊

I've tried to create a custom `Shell` or set the option on the component reference directly.

```
public class CustomShell : Shell
{
    public CustomShell()
    {
        NativeControl?.On<iOS>().SetLargeTitleDisplay(LargeTitleDisplayMode.Always);
    }
}

public override VisualNode Render() =>
        new CustomShell
        {
            ShellContent()
                .RenderContent(() => new MyPage())
        };
```

```csharp
public override VisualNode Render() =>
        new Shell(s => s?.On<iOS>().SetLargeTitleDisplay(LargeTitleDisplayMode.Always))
        {
            ShellContent()
                .RenderContent(() => new MyPage())
        };
```

The MauiReactor `.OniOS` extension does not seem to give me any options to set the `LargeTitleDisplayMode` or the `PrefersLargeTitles` value.

Thanks a lot for your time and help!

PS: Awesome project! 🎉 MauiReactor makes working with .NET MAUI much more fun in my opinion.

**Comment by adospace** [comment]
Hi I'm glad you like it.
I never used this property but from what I see it's just a dependency property to set to the NavigationPage and optionally to each Page opened inside it.

In MauiReactor you can set a dependency property on the native control using the Set() method so in your case (being an iOS-specific thing):

```c#
NavigationPage()
        .OniOS(_=>_.Set(MauiControls.PlatformConfiguration.iOSSpecific.NavigationPage.PrefersLargeTitlesProperty, true))
```

and optionally on the page you open inside it:

```c#
ContentPage()
        .OniOS(_ => _.Set(MauiControls.PlatformConfiguration.iOSSpecific.Page.LargeTitleDisplayProperty, LargeTitleDisplayMode.Never))
```

Anyway, you're talking about Shell but I can't find in the documentation any part where it says that the same property applies to the Shell too.

PS: I can't test the above code right now

**Comment by mario-zelger** [comment]
Your suggestions do work if there is a `NavigationPage` used. After another unsuccessful set of tries with `Shell`, it appears that there is no support for the large title display.

I might switch back to the `NavigationPage` or mock the behavior myself.

Thanks for your quick reply and all your work!

**Comment by domneedham** [comment]
> Your suggestions do work if there is a `NavigationPage` used. After another unsuccessful set of tries with `Shell`, it appears that there is no support for the large title display.
> 
> 
> 
> I might switch back to the `NavigationPage` or mock the behavior myself.
> 
> 
> 
> Thanks for your quick reply and all your work!

Hey, sorry I know this is old .. but did you ever get it working? I find the property itself is broken and I think it's a MAUI issue?

**Comment by davidortinau** [comment]
GitHub Copilot is our friend. Here's a solution to get to the native iOS API:

In `MauiProgram`:

```csharp
.ConfigureMauiHandlers(handlers =>
{
#if IOS
	handlers.AddHandler<Microsoft.Maui.Controls.Shell, CustomShellRenderer>();
#endif
})
```

Create the `CustomShellRenderer` in the Platforms/iOS folder:

```csharp
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.Handlers.Compatibility;
using Microsoft.Maui.Controls.Platform.Compatibility;
using ShellSection = Microsoft.Maui.Controls.ShellSection;

namespace BaristaNotes.Platforms.iOS;

/// <summary>
/// Custom ShellRenderer that uses CustomShellSectionRenderer with PrefersLargeTitles support. 
/// </summary>
public class CustomShellRenderer : ShellRenderer
{
    /// <summary>
    /// Set this to true to enable large titles for the entire Shell.
    /// </summary>
    public static bool PrefersLargeTitles { get; set; } = true;

    protected override IShellSectionRenderer CreateShellSectionRenderer(ShellSection shellSection)
    {
        return new CustomShellSectionRenderer(this)
        {
            ShellSection = shellSection,
            PrefersLargeTitles = PrefersLargeTitles
        };
    }
}
```

And the `CustomShellSectionRenderer` as well in the Platforms/iOS folder:

```csharp
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.Platform.Compatibility;
using UIKit;

namespace BaristaNotes.Platforms.iOS;

/// <summary>
/// Custom ShellSectionRenderer that adds support for PrefersLargeTitles on iOS.
/// </summary>
public class CustomShellSectionRenderer : ShellSectionRenderer
{
    private bool _prefersLargeTitles;

    public CustomShellSectionRenderer(IShellContext context) : base(context)
    {
    }

    /// <summary>
    /// Gets or sets whether the navigation bar should prefer large titles.
    /// </summary>
    public bool PrefersLargeTitles
    {
        get => _prefersLargeTitles;
        set
        {
            _prefersLargeTitles = value;
            UpdatePrefersLargeTitles();
        }
    }

    public override void ViewDidLoad()
    {
        base.ViewDidLoad();
        UpdatePrefersLargeTitles();
    }

    private void UpdatePrefersLargeTitles()
    {
        if (NavigationBar is null)
            return;

        if (OperatingSystem.IsIOSVersionAtLeast(11) || OperatingSystem.IsMacCatalystVersionAtLeast(11))
        {
            NavigationBar.PrefersLargeTitles = _prefersLargeTitles;
        }
    }
}
```

Low and behold, Shell with LargeTitles.

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/7e4bfa7f-2465-4906-aa55-97e21ddaaa5a" />

Issues:

- the title _should_ go into the usual title position as you scroll, but in my case that's not happening
- I _should_ be able to opt-out at the page level, but that isn't happening for me
