### ISSUE TITLE
Setting Props for Component in `ComponentHost`

### ISSUE THREAD

**Issue by nor0x** [adospace/reactorui-maui#248]
**Describe the bug**
Is there a way to set properties for a component that is integrated into a XAML page via `ComponentHost`?

Here is my component:
```csharp
partial class MyComponent : Component
{
    [Prop]
    string _message;
    
    public override VisualNode Render()
     => StackLayout(
            Label()
                .Text(_message)
...
        );
}
```
This is the way the `ComponentHost` is setup, it's then added to the `Content` of a XAML `ContentPage`
```csharp
var componentHost = new ComponentHost
{
    Component = typeof(MyComponent)
//how to set Message here?
};
```

I found that the only way to set the Component is via Type.

**Comment by adospace** [comment]
Currently is not possible, ComponentHost is considered a root component so it should not be intended to receive props.
One thing you can do, though, is use dependency injection (i.e. common services) to share info between the container app and the hosted MauiReactor component.

**Comment by nor0x** [comment]
thank you for the info - i will implement it via DI then
