### ISSUE TITLE
MauiControllsShellExtensions cannot be given disable animate to GotoAsync.

### ISSUE THREAD

**Issue by honeyhead** [adospace/reactorui-maui#254]
Is it possible to add this in the next version?

And on a different note, I’ve decided to use Shell for this project.

When using GoToAsync with // in the URL to navigate in the sequence of Login -> Main -> Login, if I navigate from Login to Main again, it seems like the cache remains, so OnMounted and Render are not called, and the previous data is retained.

While I’ve been solving this by implementing the OnAppearing event in ContentPage or notifying via Weak or Strong Messenger upon login, is there a way to ensure OnMounted or Render are called for the page I’m navigating to with GoToAsync?

If not, it doesn’t seem like the page is being unmounted with OnWillUnmount, so what would be the most ideal solution?

**Comment by adospace** [comment]
I recently fixed a problem related to the OnMounted/OnWillUnmount not being called when navigating back and forth using Shell.
Are you on the latest version of MauiReactor? Would you have a minute to create a small project that reproduces the issue?

**Comment by adospace** [comment]
Added `animate` parameter to the Shell.GotoAsync() extension methods in 2.0.49

Regarding the "OnMount/OnWillUnmount not called" problem, please open a new issue adding a sample project reproducing the problem,

Thanks
