### ISSUE TITLE
TestBug220Page.VerifyLabelOnModalPage doesn't pass anymore

### ISSUE THREAD

**Issue by powerdude** [adospace/reactorui-maui#256]
**Describe the bug**
Not sure when, but the above test now fails.

**To Reproduce**
Run the unit test

**Expected behavior**
It should pass

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by adospace** [comment]
fixed in 2.0.52 thanks for having reported it
