### ISSUE TITLE
[NET 9.0] - SetAndLoadSource moved to internal

### ISSUE THREAD

**Issue by trucidare** [adospace/reactorui-maui#258]
**Describe the bug**
The following PR has moved the SetAndLoadSource to internal and is not possible to call from user code.
Adding the resource through this code causes a crash:
[PR](https://github.com/dotnet/maui/pull/20776)

```
.UseMauiReactorApp<AppShell>(app =>
            {
                app.AddResource("Resources/Styles/Colors.xaml");
                app.AddResource("Resources/Styles/Styles.xaml");

            })
```

**To Reproduce**
1. Create an empty ReactorUI project from a template
2. Switch to net9.0-* identifiers
3. Run

**Expected behavior**
The expected behavior was that the styling and colors from the XAML files in Resources/Styling were added to the ResourceDictionary.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 15.0

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS
 - Version: 18.1

**Additional context**

*** Terminating app due to uncaught exception 'System.MethodAccessException', reason: 'Method `Microsoft.Maui.Controls.ResourceDictionary.SetAndLoadSource(System.Uri,string,System.Reflection.Assembly,System.Xml.IXmlLineInfo)' is inaccessible from method `MauiReactor.ApplicationExtensions.AddResource(Microsoft.Maui.Controls.Application,string,System.Reflection.Assembly)' (System.MethodAccessException)
   at MauiReactor.ApplicationExtensions.AddResource(Application application, String resourceName, Assembly containerAssembly)
   at A.MauiProgram.<>c.<CreateMauiApp>b__0_0(ReactorApplication app) in /Users/nilstonagel/Desktop/A/MauiProgram.cs:line 19
   at MauiReactor.MauiAppBuilderExtensions.<>c__DisplayClass0_0`1[[A.AppShell, A, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<UseMauiReactorApp>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extens
*** Terminating app due to uncaught exception 'System.MethodAccessException', reason: 'Method `Microsoft.Maui.Controls.ResourceDictionary.SetAndLoadSource(System.Uri,string,System.Reflection.Assembly,System.Xml.IXmlLineInfo)' is inaccessible from method `

**Comment by adospace** [comment]
Yes I'm waiting for the .net 9 official release to create version 3 of mauireactor specifically targeting .net 9.
Please hold on! 😉

**Comment by saint4eva** [comment]
> Yes I'm waiting for the .net 9 official release to create version 3 of mauireactor specifically targeting .net 9. Please hold on! 😉

For the .NET 9 support in version 3, would you change the styles to C# instead of xaml?

**Comment by adospace** [comment]
Unfortunately, the SetAndLoadSource method will be removed from .net 9, so I guess the only way I have to call it is by using reflection. It's a pity because this could be a problem for AOT compilation. I'm still experimenting.

I would support the XAML styling system at least in version 3 of MauiReactor but AOT compilation could have precedence in future versions, let's see.

**Comment by afriscic** [comment]
FWIW I vote for going C# all the way and AOT support

**Comment by adospace** [comment]
closing this ticket, I'm about to open a new ticket to track development for version 3 of MauiReactor targeting the .net 9
