### ISSUE TITLE
`ANDROID` not defined in the hot reload mode

### ISSUE THREAD

**Issue by dszymon** [adospace/reactorui-maui#267]
**Describe the bug**
Conditionally set some property:
```csharp
#if ANDROID
                                .Icon(MaterialOutlinedIcons.Email)
#elif IOS
                                .Icon(CupertinoIcons.Envelope)
#endif
```
it works fine in a standard build, but the condition won't be met as soon as the code is hot reloaded

**To Reproduce**
1. add compile time condition with `#if ANDROID` to set any property
2. start the app
3. the property is set
4. start `dotnet-maui-reactor -f net8.0-android`
5. trigger hot reload
6. the property is not set

**Expected behavior**
`dotnet-maui-reactor -f net8.0-[android|ios|...]` should respect defined constants

**Comment by adospace** [comment]
Hi, have you tried the full mode option?

**Comment by dszymon** [comment]
> Hi, have you tried the full mode option?
> 
> I can't try it right now but I believe that this case can only be handled correctly by the full-blow ms build engine: dotnet-maui-reactor -f [net8.0-android|net8.0-ios|net8.0-maccatalyst|windows10.0.19041.0] --mode Full
> 
> Another option is to put your platform dependant code in under Platform/Android/iOS etc OR check the platform at runtime like:
> 
> `.OnAndroid(_ => _.Icon(MaterialOutlinedIcons.Email));`

Hello, it works in `Full` mode. I'm hesitant to use `OnAndroid` and `OniOS` as it ends up in the final build.

Thank you for the fast reply and the great library

**Comment by dszymon** [comment]
> Hi, have you tried the full mode option?
> 
> I can't try it right now but I believe that this case can only be handled correctly by the full-blow ms build engine: dotnet-maui-reactor -f [net8.0-android|net8.0-ios|net8.0-maccatalyst|windows10.0.19041.0] --mode Full
> 
> Another option is to put your platform dependant code in under Platform/Android/iOS etc OR check the platform at runtime like:
> 
> `.OnAndroid(_ => _.Icon(MaterialOutlinedIcons.Email));`

Hello, it works in Full mode. I'm hesitant to use OnAndroid and OniOS as it ends up in the final build.

Thank you for the fast reply and the great library

**Comment by adospace** [comment]
For further info, since .net 9, building with AOT enabled targetting iOS calls to `.OnAndroid(_=>_...)` are trimmed out automatically.  Much probably with .NET 10 AOT will be available for Android too.
