### ISSUE TITLE
How to use the ItemsLayout property with CollectionView and how does Virtualization and mauiReactor caching work ?

### ISSUE THREAD

**Issue by AswinPG** [adospace/reactorui-maui#27]
Hi @adospace This library is just awesome. Thanks a lot for your work. I've been trying it out and I can't seem to crack how to use use the gridItemslayout with Collection View using MauiReactor. If there is a code sample available please let me know. Thanks.
And I was also wondering how virtualization works if each of the items are rendered every time (forgive me if the question is dumb I haven't got the time to dig deeper). I am really excited about this project and would like to understand it more. Thanks again :)

**Comment by adospace** [comment]
1) I think you can find helpful this example: https://github.com/adospace/reactorui-maui/blob/main/samples/MauiReactor.TestApp/Pages/AnimatedCollectionViewPage.cs

2) Regarding virtualization, it works exactly the same as the underlying control (CollectionView) so items are recycled according to the behavior of the native control under Android, iOS, etc. I'm unsure if I answered your question, but I'm here if you need more info.

Thanks

**Comment by AswinPG** [comment]
Wow that was fast. Thanks, I did understand how to change the ItemsLayout.

About virtualization, 
I saw this comment of yours https://github.com/adospace/reactorui-maui/issues/18#issuecomment-1408512198 can you please elaborate.. Thanks

**Comment by adospace** [comment]
Well, mainly it's the approach is different between MVVM and MVU but the behavior (so the virtualization) works the same.
In other words, in MauiReactor you just need to provide the CollectionView widget with a list of models and a function that renders a model into a visual:

```c#
class HomeState
{
   public Model[] Items {get;set;}
}

class Home: Component<HomeState>
{
  public override Render()
  {
    return new CollectionView()
       .ItemsSource(State.Items, item => new Label(item.Label));
  }
}
```

MauiReactor tasks care of reusing native controls used to render the item.

**Comment by AswinPG** [comment]
I understood some of it. I would like to know more on this. From what I understand MAUI CV virtualization and mauiReactor caching are totally different right ?

**Comment by adospace** [comment]
Sorry, but I'm not sure what you mean by totally different, MAUI CV virtualization is essentially what is provided by the native control. MauiReactor just creates the DataTemplate on fly from the tree of visual nodes returned by the render function passed to the ItemsSource property.

**Comment by AswinPG** [comment]
Thanks I get it :)

**Comment by adospace** [comment]
Further info is described here: https://adospace.gitbook.io/mauireactor/q-and-a/does-this-support-observablecollection-for-collectionview
