### ISSUE TITLE
What would be the best way to create top and bottom tabs in mauiReactor

### ISSUE THREAD

**Issue by AswinPG** [adospace/reactorui-maui#28]
The current implementation of shell in maui is pretty limited in terms of UI customisation. If we were to create tabs using components and writie the logic to display each tab without shell, would it affect performance ? Which is the best way to go ?

**Comment by adospace** [comment]
In MauiReactor (as in MAUI itself) you can use the Shell (if it's enough to recreate the design of the app) or go by yourself re-creating tabs etc in code, maybe you can look at the samples folder or at the KeeMind (https://github.com/adospace/kee-mind) sample app to be inspired.
