### ISSUE TITLE
Supprot windows development?

### ISSUE THREAD

**Issue by nameofSEOKWONHONG** [adospace/reactorui-maui#3]
Hello. I'm plan to proceed with Windows platform development using maui.
It is currently impossible to proceed.
Do you have a support plan?

**Comment by adospace** [comment]
Hum, I'm not sure what you mean by "it's impossible to develop Windows applications in Maui", Maui supports Windows platform development and you can write a Windows application in MauiReactor too.

**Comment by nameofSEOKWONHONG** [comment]
Sorry. You didn't install the maui workload and components.
