### ISSUE TITLE
Is it possible to animate a strokeshape for border?

### ISSUE THREAD

**Issue by AswinPG** [adospace/reactorui-maui#32]
I tried to animate the Border corner radius by adding `double CornerRadius` as a state.

`.StrokeShape(new RoundRectangle()
                                 .CornerRadius(() => new CornerRadius(State.CornerRadius)))`
                                 
   `SetState((s) =>
      {
          s.CornerRadius = v;
      },invalidateComponent:true);`
      
      
      The above code does not animate the corner radius. How can it be achieved ?

**Comment by adospace** [comment]
Yes, it's a .NET MAUI itself issue I was aware. 
The shape passed to the border is only used one time when the border is created but then any change applied to the shape is not reflected in the border. 

Said that I recognize that is something should work instead, so I'm going to fix this in the coming new version that forces the update temporarily removing and re-adding the shape to the border
