### ISSUE TITLE
What does RepeatForever and Loop in AnimationController do ?

### ISSUE THREAD

**Issue by AswinPG** [adospace/reactorui-maui#33]
Even if don't add `RepeatForever()` the animation seems to be running non stop. 
`Loop()` works differently when `RepeatForever()` is added and not added. 
Also is there a way to make the animation happen only once ?
Thanks :)

**Comment by adospace** [comment]
hum, have you seen the AnimationShowcasePage test page inside TestApp project: it let you experiment with the different properties of the AnimationContainer.
Basically, there are 3 properties:
public double InitialDelay: Set the initial of the animation
public bool Loop: (default: false) set whether the animation should come back to the previous value or not, i.e. looping.
public int? IterationCount; (default: 1) If set, is the number of iterations, so setting it to 1 it runs just once.

RepeatForever() is a shortcut for IterationCount and set it to null, so it repeats forever
