### ISSUE TITLE
Handling OnBackButtonPressed in a custom NavigationPage

### ISSUE THREAD

**Issue by crimer** [adospace/reactorui-maui#36]
Hi, I have a custom Navigation Page in my project that inherits from NavigationPage and in it I can override the behavior of pressing the back button. It looks like this

![image](https://user-images.githubusercontent.com/46929800/223647983-1885c531-7d07-4137-a974-0cd32363db2b.png)

![image](https://user-images.githubusercontent.com/46929800/223648297-1623c97b-52b7-437e-b86c-b089a3e882d4.png)

Every VM of each page can override its behavior of navigation back click.
Inheritance from MauiReactor.NavigationPage does not allow me to override Navigation Back Button Click behavior.

How do I do the same behavior that was when using the MVVM architecture?

**Comment by adospace** [comment]
Yeah, I forgot to port this part from the XF library, for now, please use a code like this:

```csharp
public override VisualNode Render()
{
    return new NavigationPage
    {
        new ContentPage()
        {

        }
        .Set(MauiControls.Shell.BackButtonBehaviorProperty, new MauiControls.BackButtonBehavior
        {
            Command = new MauiControls.Command(() => 
            {
                //your code
            })
        })
    };
}
```

I'm going to add some helper functions for this that will let developers just set the action to execute (but the underlying stuff would be more or less this).

The above code will work on future versions as well.

**Comment by crimer** [comment]
I get it, thanks for the help
