### ISSUE TITLE
Navigating to another page

### ISSUE THREAD

**Issue by MaTToX3** [adospace/reactorui-maui#37]
Hello! Just found out about this great library and giving it a test run, to maybe finally ditch the MVVM (in the future of course!). 

Anyways, I have quickly ran into the issue regarding the navigation. In the documentation it appears it is straightforward to navigate to another page so I gave it a try:

Added a button to the existing MainPage:

```C#
new Button("Navigate to Another page")
     .OnClicked(HandleNavigateClick)
```

Defined the click handler like so:

```C#
async void HandleNavigateClick()
{
    await Navigation.PushAsync<AnotherPage>(true);
}
```

And then the second page:

```C#
internal class AnotherPage : Component
{
    public override VisualNode Render()
    {
        return new ContentPage
        {
            new VStack
            {
                new Label("This is another page")
            }
        };
    }
}
```

And well, nothing happens - the method for navigating is called but no navigation happens - no errors or anything out of order. Did I miss something?

Have to say, the developer experience is amazing - being able to constantly run the application and just change things is just crazy good. Not something I can say about the official Hot Reload... 

Best regards,
Matej

**Comment by adospace** [comment]
Hi, thank you for your interest, did you see this documentation article: https://adospace.gitbook.io/mauireactor/deep-dives/navigation

do you have a navigationpage?

**Comment by MaTToX3** [comment]
No, I did not have it, I just modified the first page with button. My mistake. Thank you for a quick reply!
