### ISSUE TITLE
CarouselView usage

### ISSUE THREAD

**Issue by aokocax** [adospace/reactorui-maui#38]
First of all, thanks for the great project.
I can easily add simple controls into the project, but I have difficulties with controls that require initialization such as CarouselView.
Could you please share sample code for CarouselView?

**Comment by adospace** [comment]
Hi, this should work just fine:

```csharp
new CarouselView()
    .ItemsSource(Enumerable.Range(1, 10)
        .Select(_=>$"Item{_}"), _ => new Label(_))
```

essentially it's like other ItemsView-derived controls like CollectionView: you have to pass in the items source and a render method.

**Comment by adospace** [comment]
ok, for it to work I need to change a thing on the library in the next version you'll able to add it too,  please stay tuned :)

**Comment by adospace** [comment]
I've added a sample page in the test app that shows how to use the indicator view (you need to upgrade to latest version of MauiReactor):

```csharp
new Grid("* 40", "*")
{
    new CarouselView(r => _carouselView = r)
        .ItemsSource(Enumerable.Range(1, 5), _=> new Label($"Page{_}").VCenter()),

    new IndicatorView(r =>
    {
        if (_carouselView != null)
        {
            _carouselView.IndicatorView = r;
        }
    })
    .HCenter()
    .VCenter()
    .IndicatorTemplate(() => new Label("Test"))
    .VisualState("CommonStates", "Normal", MauiControls.Label.TextColorProperty, Colors.Black)
    .VisualState("CommonStates", "Selected", MauiControls.Label.TextColorProperty, Colors.White)
    .GridRow(1),
}
```

**Comment by aokocax** [comment]
@adospace , you are great, thank you. You're going to have to convert my projects to MauiReactor :).
This has been my favorite project for a long time. I also plan to make small contributions.
