### ISSUE TITLE
ToolbarItem usage

### ISSUE THREAD

**Issue by crimer** [adospace/reactorui-maui#40]
Hello, I made a method to create a ToolBarItem, but the page does not have a method for adding it, how can I add it to a page?
![image](https://user-images.githubusercontent.com/46929800/224323768-c0aef70d-0f5f-4327-9cff-119834ff4d50.png)

**Comment by adospace** [comment]
Just put the ToolbarItem inside a page:

```csharp
new ContentPage()
{
CreateToolbarItem1(),
CreateToolbarItem2(),
...
}
```
the same works for the MenuItems

**Comment by crimer** [comment]
Yes, it worked, thank you
