### ISSUE TITLE
Is there a GestureRecognizer sample code

### ISSUE THREAD

**Issue by flexi-git** [adospace/reactorui-maui#42]
Hi Ado, I hope you're doing well. I would like to ask if there are sample code for gesture recognizer (ie. swipe(direction: left; right; top; bottom), drag and drop) in your sample repositories that I can look and try. I think the common use case is swipe to reveal the menu choices for delete or edit. Thank you

**Comment by adospace** [comment]
Hi, usually it's enough to create an object of type `SwipeGestureRecognizer` like shown in this example:

```csharp
new VStack(spacing: 2)
{
    new Label(_name),
    new Label(_label),

    new SwipeGestureRecognizer()
        .Direction(SwipeDirection.Right)
        .Threshold(10)
        .OnSwiped(OnSwipedRight)
}
```

but if you need to move something when the user swipes an object to the right/left, you may need a CanvasView with the PointInteractionHandler.
Can you specify better where you need the swipe operation? inside a collectionview?

**Comment by flexi-git** [comment]
Thank you Ado, your code works perfectly fine and the implementation is a breeze.
I'll be using swipegesture operation in my collectionview, if the user swipe halfway I'll be showing a menu to delete or edit, but if the user swipe all the way to the right/left I'll be calling the delete method.

Also, how can I pass the direction SwipedEventArgs parameter in my method if let say I have two swipegesture?
`new VStack(spacing: 2)
{
    new Label(_name),
    new Label(_label),

    new SwipeGestureRecognizer()
        .Direction(SwipeDirection.Right)
        .Threshold(10)
        .OnSwiped(onSwiped),
new SwipeGestureRecognizer()
        .Direction(SwipeDirection.Left)
        .Threshold(10)
        .OnSwiped(onSwiped)
}

async void onSwipe(object sender, SwipedEventArgs e)
{
switch (e.Direction)
        {
            case SwipeDirection.Left:
                // Handle the swipe
                break;
            case SwipeDirection.Right:
                // Handle the swipe
                break;
        }
}`

Or do I need two method one for SwipeLeft and antoher one for SwipeRight?

**Comment by adospace** [comment]
Yes, you can define 2 methods SwipeLeft or SwipeRight or you can do as you did above with one single method accepting (object sender, SwipedEventArgs e).

I'm going to provide a sample that shows the swiping behavior in the test app

**Comment by flexi-git** [comment]
Yes please, I appreciate if you can provide sample code that show swipe behavior and PanGesture will help us in future project. Thank you![image](https://user-images.githubusercontent.com/36848606/225862614-526bb03b-d07c-4ded-ab9f-1d900c7817a6.jpeg)
