### ISSUE TITLE
Set Window size?

### ISSUE THREAD

**Issue by phollyer** [adospace/reactorui-maui#44]
Hi Ado,

I've just started looking at Maui Reactor and really like what you're doing 👍 

Is it currently possible to set the window size for a Desktop app? I'm interested in setting the start up size along with minimums and maximums for height and width. I've been through the docs but couldn't find anything and I've seen some examples wrt Maui, but can't figure out how to use those with ReactorUI or if they're even relevant.

(I've just started my .NET journey, so it's all a bit new at the moment...)

Thanks 
Paul

**Comment by phollyer** [comment]
Many Thanks, I'll try implementing it tomorrow.

**Comment by adospace** [comment]
The latest version of MauiReactor contains some enhancements on Window support, please take a look at the new documentation page: https://adospace.gitbook.io/mauireactor/components/window
