### ISSUE TITLE
Should this work with Visual Studio's hot reload?

### ISSUE THREAD

**Issue by NickDarvey** [adospace/reactorui-maui#47]
I understand that there is a dotnet tool, `dotnet-maui-reactor`, which gives us a hot reload dev experience.  Visual Studio and the default MAUI template also supports a hot reload dev experience. 

I'd like to build a ReactorUI app in Visual Studio using the built-in hot reload experience.

I was wondering if there was anything fundamental to ReactorUI implementation or Visual Studio's implementation of hot reload which would mean this is not possible?

## Repro

1. `dotnet new maui-reactor-startup`
2. Open the csproj in Visual Studio
3. Debug with the Windows Machine profile

## Expected

Hot reload works like the default MAUI template.

## Actual

Hot reload shows as connected from Visual Studio but not connected from the toolbar inside the Windows app.

Additionally, I see `SerializationException`s in the output window.

```
System.Runtime.Serialization.SerializationException: 'Element ':item' contains data of the 'http://schemas.datacontract.org/2004/07/Xamarin.HotReload:UpdateDelta' data contract. The deserializer has no knowledge of any type that maps to this contract. Add the type corresponding to 'UpdateDelta' to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding it to the list of known types passed to DataContractSerializer.'
```

## System info

- ReactorUI.Maui 1.0.108
- dotnet 7.0.202
- Visual Studio 17.5.2

**Comment by adospace** [comment]
Hi, support for the Visual Studio built-in hot-reload experience release is around the corner, just need to prepare some documentation and I'll release it.
If you want to get an early peek at how it works please use the [metadat-update-handler](https://github.com/adospace/reactorui-maui/tree/metadat-update-handler) branch.


https://user-images.githubusercontent.com/10573253/226900151-51aa865e-91bd-486c-879b-8be955f2f326.mp4

**Comment by NickDarvey** [comment]
Brilliant! Thank you.
