### ISSUE TITLE
.WindowTitle has no effect

### ISSUE THREAD

**Issue by phollyer** [adospace/reactorui-maui#48]
Hi,

Setting the WindowTitle on the following has no effect, the Window Title remains as the App name, am I missing something?

MainPage.cs
```
using MauiReactor;

namespace MyApp.Pages;

class MainPageState
{
    public bool IsRegistered { get; set; } = false;
    public string Token { get; set; }
}

class MainPage : Component<MainPageState>
{
    protected override void OnMounted()
    {
        SetState(s =>
            {
                s.IsRegistered = Preferences.Get("isRegistered", false);
                s.Token = Preferences.Get("token", null);
            }
        );

        base.OnMounted();
    }

    public override VisualNode Render()
    {
        bool hasToken = State.Token != null;

        VisualNode page = new RegisterPage();

        if (State.IsRegistered && hasToken)
        {
            page = new NavigationPage()
            {
                new HomePage()
            };
        }
        else if (State.IsRegistered)
        {
            page = new SignInPage();
        }

        return page;
    }
}
```

RegisterPage.cs
```
namespace MyApp.Pages;

class RegisterPage : Component
{
    public override VisualNode Render()
    {
        return new ContentPage()
        {
        }
        .WindowTitle("Register")
        ;
    }
}
```

**Comment by phollyer** [comment]
Ah ok thanks for the tip.

I'm using version 1.0.114

**Comment by phollyer** [comment]
I've just seen on the ReadMe that you're up to v 1.0.115, I don't see that in my list of Nuget packages. Will try to upgrade and try .WindowTitle again with the latest version.

**Comment by phollyer** [comment]
Found v1.0.115 in the Updates tab, so updated now, but no change.

MainPage.cs now looks like this:
```
using MauiReactor;
using Microsoft.Maui.Storage;

namespace MyApp.Pages;

class MainPageState
{
    public bool IsRegistered { get; set; } = false;
    public string Token { get; set; }
}

class MainPage : Component<MainPageState>
{
    protected override void OnMounted()
    {
        State.IsRegistered = Preferences.Get("isRegistered", false);
        State.Token = Preferences.Get("token", null);
            
        base.OnMounted();
    }

    public override VisualNode Render()
    {
        return new NavigationPage()
        {
            SelectPage()
        };
    }

    private VisualNode SelectPage()
    {
        bool hasToken = State.Token != null;

        VisualNode page = new RegisterPage();

        if (State.IsRegistered && hasToken)
        {
            page = new HomePage();
        }
        else if (State.IsRegistered)
        {
            page = new SignInPage();
        }

        return page;
    }
}

```

**Comment by adospace** [comment]
ok now I see you use a parent container like NavigationPage, you should set then the WindowTitle on the NavigationPage that is the root:

```csharp
return new NavigationPage()
{
    SelectPage()
}
.WindowTitle("My Title");
```

**Comment by phollyer** [comment]
Just tried that and no effect. I've got to go out now but tomorrow morning I'll put something minimal on github and post the link.

**Comment by phollyer** [comment]
[Here's](https://github.com/phollyer/MauiReactor-WindowTitle) the link to the repo. The Window Title should change to "My Window" but remains as  "WindowTitle".

**Comment by adospace** [comment]
ok maybe it's a macOS issue as under Windows seems working fine:
![image](https://user-images.githubusercontent.com/10573253/227206011-91f28633-8ad7-4659-8d46-0b7c69b7e155.png)

I'll test it on mac os...

**Comment by adospace** [comment]
yes, I confirm that is a MacOS issue but not related to MauiReactor: i.e. if you try to create a standard Maui application and set the window title it doesn't work either.
So for now I guess I can't do much on my side and wait for a fix from Maui team (not sure if it's something already fixed in.net 8 preview)

**Comment by phollyer** [comment]
Ok thanks for looking into it.
