### ISSUE TITLE
Application lifecycle events

### ISSUE THREAD

**Issue by NickDarvey** [adospace/reactorui-maui#49]
Is there a recommended way to hook into application lifecycle events?

It looks like they're available on `ReactorApplication<>` if I derive my own application class 

https://github.com/adospace/reactorui-maui/blob/7de43399d1a2c891910c9db501d2b173f7614d7d/src/MauiReactor/ReactorApplication.cs#L296-L315

and instantiate it myself.

https://github.com/adospace/reactorui-maui/blob/7de43399d1a2c891910c9db501d2b173f7614d7d/src/MauiReactor/ReactorApplication.cs#L327-L334

**Comment by adospace** [comment]
Hi, I don't think you need to override the Application type (even if I could allow it in the future).

You could just provide your Window and attach the events you need:

```csharp
class MainPage : Component
{
    public override VisualNode Render()
    {
        return new Window
        {
            new ContentPage
            {
            }
        }
        .OnCreated(OnMainWindowCreated)
        .OnStopped(OnMainWindowStopped)
        ;
    }

    private void OnMainWindowCreated()
    {
        System.Diagnostics.Debug.WriteLine("Window created");
    }

    private void OnMainWindowStopped()
    {
        System.Diagnostics.Debug.WriteLine("Window stopped");
    }
}
```
For others looking at this thread this is the list of callbacks provided by the Application type:
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle?view=net-maui-7.0
