### ISSUE TITLE
Help with the Docs?

### ISSUE THREAD

**Issue by phollyer** [adospace/reactorui-maui#51]
Hi Ado,

I really like what you are doing with this project, and as a thank you for your help, I'd be happy to help with the docs if that's something that you are up for(?). Initially I'm thinking I could proof read and fix some of the syntax errors that have crept in due to English not being you first language. Later on, as I get to grips with ReactorMaui, I'd be happy to add some code snippet examples for common use cases.

I can't offer to help with the ReactorMaui code, still learning C#, I've spent the last 5 or so years working with Elm (MVU), which is why I was attracted to ReactorMaui, so would be more than happy to help out where I can.

**Comment by adospace** [comment]
Hi, thank you so much for your offer, by the documentation you mean the gitbook documentation site (https://adospace.gitbook.io/mauireactor/)?

**Comment by adospace** [comment]
I've created a new GitHub repo with the documentation, please open pr there to make changes/integrations, I'll be happy to review and merge it.
https://github.com/adospace/reactorui-maui-docs

Thank you again for your interest!

**Comment by phollyer** [comment]
Cool, I'll take a look 👍
