### ISSUE TITLE
HotReload console error

### ISSUE THREAD

**Issue by BernhardPollerspoeck** [adospace/reactorui-maui#57]
Hi, i started testing this package. but i have a problem with the console. Here a quick screenshot of my  error. I could not find more in the docs. i suspect my problem is really simple, but i cant figure it out.

![image](https://user-images.githubusercontent.com/105512133/229886375-62cc9040-f30a-48a1-b2da-436f15eef486.png)

**Comment by adospace** [comment]
you have to pick one platform for example
dotnet-maui-reactor -f net7.0-android

**Comment by BernhardPollerspoeck** [comment]
Hi, 

thank you for your amazing fast response. I now tried the windows platform, but now i am facing multible errors

*   sdk assemblies seem to be not there(i doubt, since the app and all other maui apps on net7.0 run perfectly
*   the exe was not found( since it it in a sub folder.)

again i attatched afull screenshot of the log output(please advice if a text paste would be better). Is this still a mistake on my side?

![](https://user-images.githubusercontent.com/105512133/229891804-3e567a60-951e-4066-9af4-9c7b0f8f82a4.png)

**Comment by adospace** [comment]
yes seems you have to install the winui developer pack, have you tried to build the app in visual studio 2022 it should guide thru the installation of the workload

**Comment by BernhardPollerspoeck** [comment]
the app runs perfectly from vs22. also 4 other maui projects (some created in net 6 and ported, and some created in net7 are working fine. 

i am taking a look into the winui pack to install. i respond back.

**Comment by stillnurs** [comment]
I'm having errors in console as well with hot-reload. Fresh project.
![image](https://user-images.githubusercontent.com/67423522/230126713-5e9a1154-f82d-4820-8dcd-714fd3bc323b.png)

**Comment by stillnurs** [comment]
> This is another case, I think you're hot reloading an Android app. The error is caused by the adb.exe program not starting correctly. A few things to check:
> 
> 1. local port 45820 is already occupied
> 2. adb program itself is not working fine
> 
> The adb used by hot-reload should be located inside the folder: Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), "Android", "android-sdk", "platform-tools", "adb.exe")

I found that adb.exe is in this location: C:\Android\android-sdk\platform-tools\adb.exe
Hope it's correct location, since I never touched any installation settings of android related packages.
Don't have ideas what to do with it now.

**Comment by BernhardPollerspoeck** [comment]
ive ipdated VS to the latest 17.5 Version, installed the sdk°s and still the same errors.  
\- the build fails with the following error:

C:\\Program Files\\dotnet\\sdk\\7.0.202\\Microsoft.Common.CurrentVersion.targets(1229,5): error MSB3644: The reference assemblies for Windows,Version=v10.0.19841 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks \[E:\\Gewerbe\\PollerspÃ¶ck\\smart home\\source\\smart.app\\smart.app.csproj::TargetFramework=windows10.0.19841.0\]

*   the reload looks for the exe in the wrong location

Unable to hot reload the application:  
System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\\Gewerbe\\Pollersp”ck\\smart home\\source\\smart.app\\bin\\Debug\\windows10.0.19841.0\\smart.app.exe'.  
  at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)  
  at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable\`1 unixCreateMode)  
  at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable\`1 unixCreateMode)  
  at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable\`1 unixCreateMode)  
  at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)  
  at MauiReactor.HotReloadConsole.HotReloadClientFull.CompileProject(Stream stream, Stream pdbStream, CancellationToken cancellationToken) in C:\\projects\\reactorui-maui\\src\\MauiReactor.HotReloadConsole\\HotReloadClientFull.cs:line 53  
  at MauiReactor.HotReloadConsole.HotReloadClient.ConnectionLoop(CancellationToken cancellationToken) in C:\\projects\\reactorui-maui\\src\\MauiReactor.HotReloadConsole\\HotReloadClient.cs:line 151

Is there some real solution here?

**Comment by adospace** [comment]
@BernhardPollerspoeck Sorry but I'm not sure what I can do to help, seems that in your scenario MsBuild fails to build your solution complaining about the SDK targeting windows10.0.19841.0 is not installed

@stillnurs adb should be correctly installed and working to make hot-reload working

**Comment by rctec-at** [comment]
Hi @BernhardPollerspoeck we´ve encountered the same Problems you are facing. After out initial 3 Day Tech Evaluation period, we also could not get this running on Windows. Do the mobile platforms work for you?

**Comment by BernhardPollerspoeck** [comment]
Hello together. i tested iOS also, but here i ran into other hot reload problems. Since so early in testing this framework ive ran into unresolveable problems, i dont think i will proceed.   
best of luck for the packages future. looks great.
