### ISSUE TITLE
Navigation.PushAsync not working

### ISSUE THREAD

**Issue by DevPlus31** [adospace/reactorui-maui#61]
`new Button("Open Window")
                        .OnClicked(async() =>
                        {
                            await Navigation.PushAsync<FullColorWindow>();
                        })`

I added this code to MainPage (demo) and created a new component named FullColorWindow with its own children items. 

**Expected behavior** 
App displays the component named FullColorWindow

**What happened**
Nothing after clicking on the button multiple times nothing happens
PS: no errors & exception.

Thank you.

**Comment by adospace** [comment]
can you show some code? for example the code of the FullColorWindow component

**Comment by DevPlus31** [comment]
Sure
`using System;
using MauiReactor;
using MauiReactor.Canvas;

namespace ColorApp.Pages;

class FullColorWindowState
{
    public Color Color { get; set; }
}

class FullColorWindow : Component<FullColorWindowState>
{
    public override VisualNode Render()
    {
        return new ContentPage
        {
           new CanvasView
           {
               new Box()
                    .BackgroundColor(State.Color)
           }

        };
    }
}`

**Comment by adospace** [comment]
Hum, is it possible that you aren't using a navigation system? for example the NavigationPage? 

```csharp
class MainPage : Component
{
    public override VisualNode Render()
    {
        return new NavigationPage
        {
            new ContentPage
            {
                new ScrollView
                {
                    new VerticalStackLayout
                    {
                        new Button("Open Child Page")
                            .OnClicked(OnOpenChildPage)
                            .HCenter()
                    }
                    .VCenter()
                    .Spacing(25)
                    .Padding(30, 0)
                }
            }
        };
    }

    async void OnOpenChildPage()
    {
        await Navigation.PushAsync<FullColorWindow>();
    }
}

class FullColorWindowState
{
    public Color Color { get; set; } = Colors.Red;
}

class FullColorWindow : Component<FullColorWindowState>
{
    public override VisualNode Render()
    {
        return new ContentPage
        {
           new CanvasView
           {
               new Box()
                    .BackgroundColor(State.Color)
           }
        };
    }
}
```

if so can you try to follow this documentation article: https://adospace.gitbook.io/mauireactor/deep-dives/navigation and see if it's working for you?

**Comment by DevPlus31** [comment]
Yes I am followed the documentation and it didn't work 
Forgot to say I am on MacOS 13.2.1

**Comment by adospace** [comment]
Ok so you don't have the navigation page on the mainpage

**Comment by DevPlus31** [comment]
Yes it's into different file, I copied FullColorWindow to MainPage file it's still doesn't work.

**Comment by DevPlus31** [comment]
Sorry I saw my mistake now I forgot the NavigationPage parent

**Comment by DevPlus31** [comment]
BTW is there a way to Navigate to another page without NavigationPage?

**Comment by freever** [comment]
@DevPlus31 I think the answer to #56 might be relevant to your question

**Comment by adospace** [comment]
@DevPlus31 In standard dotnet maui it's required to have either a NavigationPage as a parent or a Shell to navigate between pages (MAUI itself should warn in case neither of them is available but maybe there is a good reason for that I'm not aware of).

NavigationPage: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage?view=net-maui-7.0
Shell: https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation?view=net-maui-7.0

I agree with @freever that maybe you're looking for a way to just swap the root content page of a Window: answer to #56 could be useful in that case

**Comment by DevPlus31** [comment]
Thank you
