### ISSUE TITLE
NotSupportedException when using non-reactorui controls

### ISSUE THREAD

**Issue by JaneySprings** [adospace/reactorui-maui#70]
Hello. Thank you for this library! 

I'm trying to use CommunityToolkit views with Reactor.Maui:
```csharp
class MainPage : Component<MainPageState> {
    public override VisualNode Render() {
        return new ContentPage {
            new ScrollView {
                new VerticalStackLayout {
                    new Button(State.Counter == 0 ? "Click me" : $"Clicked {State.Counter} times!")
                        .OnClicked(()=>SetState(s => s.Counter++))
                        .HCenter(),
                    new AvatarView {
                        Text = "ZS"
                    }
                }
                .VCenter()
                .Spacing(25)
                .Padding(20, 0)
            }
        };
    }
}
```
But I have a following exception:
<img width="1440" alt="Screenshot 2023-05-01 at 12 53 37" src="https://user-images.githubusercontent.com/48021947/235432179-d3384c7e-f275-4ee9-8c95-4450a8a83dce.png">

Its also happens when using MAUI controls:
<img width="879" alt="Screenshot 2023-05-01 at 12 57 15" src="https://user-images.githubusercontent.com/48021947/235432340-30f3667e-2cf4-49c3-8450-7d4d85792ff5.png">

Maybe I need to write some kind of wrapper for these classes? For example:
```csharp
class ReactorUIAvatarView: CommunityToolkit.AvatarView {
    override...
}
```

**Comment by JaneySprings** [comment]
Yep. I tried this:
```csharp
public class MyControl: View<CommunityToolkit.Maui.Views.AvatarView> {
}
```
Works fine.

BTW: Thank you for this awesome library!

**Comment by adospace** [comment]
Yeah, you can't directly put Maui controls under mauireactor elements, you need a wrapper.
MauiReactor includes a convenient source generator, please gett a look at this guide:
https://adospace.gitbook.io/mauireactor/components/wrap-3rd-party-controls

Said that, I'm probably going to provide a package with all the wrappers for common libraries like the Community toolkit

**Comment by JaneySprings** [comment]
I think you just need to add this link to the readme.
Common libraries are updated very often and you may not keep up with them.

**Comment by adospace** [comment]
The link to the documentation is present in the readme
