### ISSUE TITLE
Hot reload fails when using partial class with GeneratedRegex

### ISSUE THREAD

**Issue by Code-DJ** [adospace/reactorui-maui#73]
Hot reload throws an error if GeneratedRegex is used.

#### To test, add the following class to any project and try using hot reload:
```c#
public partial class Test
{
    [System.Text.RegularExpressions.GeneratedRegex("-")]
    private static partial System.Text.RegularExpressions.Regex MyRegex();
}
```

#### You will get the following error:
error CS8795: Partial method 'Test.MyRegex()' must have an implementation part because it has accessibility modifiers.

**Comment by adospace** [comment]
Hi, simple mode can't handle source generators, for that to work you need to opt in for full mode: add `-m Full` to `dotnet-maui-reactor` command.

Another option is to put this function in a secondary assembly/project linked to the main project that will not be hot-reloaded.

Hope it helps!

**Comment by Code-DJ** [comment]
Cool, thanks for the amazing library!
