### ISSUE TITLE
EditableCollectionView in TestApp sample project doesn't update

### ISSUE THREAD

**Issue by Dimension4** [adospace/reactorui-maui#75]
I tried to figure out why my `CollectionView` doesn't update, despite me following the [docs](https://adospace.gitbook.io/mauireactor/q-and-a/does-this-support-observablecollection-for-collectionview#read-write-collectionview), so I've tried to run the [MauiReactor.TestApp](https://github.com/adospace/reactorui-maui/tree/main/samples/MauiReactor.TestApp) sample project on Windows Desktop, and that one also doesn't update the `CollectionView` when I click "Add Item" or "Remove Item".

I'm using Reactor.Maui version 1.0.124

**Comment by adospace** [comment]
Unfortunately, .NET MAUI CollectionView itself seems to have strange behaviors under Windows. 
Internally, MauiReactor just set the ItemSource property to a collection that implements INotifyCollectionChanged and everything works on other platforms. 
Under Windows, it seems to require a full-blow ObservableCollection object.
I guess this behavior will be corrected in future releases but for now, I consider this a bug in MauiReactor and I'm going to fix this in the next version 125.
Thanks for reporting this.
