### ISSUE TITLE
How to use DynamicResource and Styles

### ISSUE THREAD

**Issue by gpproton** [adospace/reactorui-maui#8]
I've been trying to migrate a C# Markup code to reactorui-maui but there's been no way to use DynamicResource, StaticResource or the the Style method.
I already prepare lot of XAML style i don't want to design controls individually.

**Comment by gpproton** [comment]
Thanks for the quick reply, but what I meant using styles from resource dictionary with any components,
please see examples below.

### CSharp Markup example

```csharp
new Button() {
           ImageSource = Icons.Google,
           ContentLayout = new ButtonContentLayout(ButtonContentLayout.ImagePosition.Left, 32)
       }
      .Text("Sign in with Google")
      .DynamicResource(StyleProperty, "ButtonAuth")
      .CenterVertical()
      .BindCommand(nameof(AuthViewModel.NavigateToHomeCommand)),
```

### MAUI-Reactor example

```csharp
new Button("Sign in with Google", async () => await Mac.Shell.Current.GoToAsync($"//{nameof(HomeView)}"))
        .ImageSource(Icons.Google)
        .ContentLayout(new Mac.Button.ButtonContentLayout(Mac.Button.ButtonContentLayout.ImagePosition.Left, 32))
        .HCenter().VCenter()
// No dynamic resource method available
```

### Style example
```xaml
<?xml version="1.0" encoding="UTF-8"?>
<?xaml-comp compile="true" ?>
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <Style x:Key="ButtonAuth" TargetType="Button">
        <Setter Property="Padding" Value="48, 16, 48, 16" />
        <Setter Property="Margin" Value="24, 16, 24, 8" />
        <Setter Property="FontSize" Value="16" />
        <Setter Property="BackgroundColor" Value="Transparent" />
        <Setter Property="BorderColor" Value="{DynamicResource Tertiary}" />
        <Setter Property="BorderWidth" Value="1" />
        <Setter Property="TextColor" Value="{DynamicResource Tertiary}" />
    </Style>
</ResourceDictionary>
```

**Comment by adospace** [comment]
ok understand, so you can actually do a couple of things:

1) Set the style of the element to the Style resource (same as using StaticResource):
`.Set(VisualElement.StyleProperty, Application.Current.Resources["ButtonAuth"])`

2) If you _really_ want to connect the style to a dynamic resource:
`new Button(buttonRef => buttonRef?.SetDynamicResource(VisualElement.StyleProperty, "ButtonAuth"))`
BUT: please note that in MauiReactor the component is refreshed every time it's invalidated from a state change or child component invalidation, **so it's not actually required to bind a dependency property to a DynamicResource**.
In other words, I strongly suggest you change any DinamicResource to StaticResource.

and even better replace (gradually) any style resource in a compiled c# style-like code like this:

```csharp
static class MyThemeExtensions
{
    public static Button WithAuthStyle(this Button btn)
    {
       btn.Padding = new Thickness(48,16,48,16);
       .....
    
       return btn;
    }
}

//and use it like this:
new Button("Sign in with Google", async () => await Mac.Shell.Current.GoToAsync($"//{nameof(HomeView)}"))
        .ImageSource(Icons.Google)
        .ContentLayout(new Mac.Button.ButtonContentLayout(Mac.Button.ButtonContentLayout.ImagePosition.Left, 32))
        .HCenter().VCenter()
        .WithAuthStyle()
```

**Comment by adospace** [comment]
I've created a documentation page for this: https://adospace.gitbook.io/mauireactor/deep-dives/using-xaml-resources
