### ISSUE TITLE
Back button behavior

### ISSUE THREAD

**Issue by crimer** [adospace/reactorui-maui#80]
Hi I tried to handle custom callback on the back button click, but it's not working.

```
public class TestPage : Component
{
    public override VisualNode Render()
    {
        return new ContentPage()
            {
                new Button("next")
                    .OnClicked(async () =>
                    {
                        await Navigation?.PushAsync<TestPage>();
                    })
            }
            .Title("Test")
            .OnBackButtonPressed(() =>
            {
                Debug.WriteLine("adsd");
            })
            .BackButtonIsVisible(true)
            .BackButtonIsEnabled(true);
    }
}
```

```
public class App : Component
{
    public override VisualNode Render() => new NavigationPage()
        {
            new TestPage()
        };
}
```

**Comment by adospace** [comment]
Hi, just to understand, are you navigating to the same page TestPage?

**Comment by crimer** [comment]
Yes, purely for the test

**Comment by Code-DJ** [comment]
@crimer I tried your code and it works fine on iOS.

- Opens up with no back button.
- Click next button in the center of the screen.
- Takes you to a new Test page with "< Test" back button at the top.
- Click "< Test" back button at the top and it bring me back to the first page without back button.

**Comment by adospace** [comment]
Tested and working on Android and Windows too, I'm closing this, let me know if you have more info
