### ISSUE TITLE
Sample DataTemplateSelector

### ISSUE THREAD

**Issue by Code-DJ** [adospace/reactorui-maui#82]
Hi, is there a sample for DataTemplateSelector. I tried the github search but didn't find it.

I'm able to create my own class that inherits MauiControls.DataTemplateSelector but not sure where to set it. 

```csharp
    public class MyDataTemplateSelector : DataTemplateSelector
    {
        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            if (item is not MyClass myItem)
                return OnSelectTemplate(item, container);

            return myItem.CellType switch
            {
                MyViewCellType.A => new DataTemplate(typeof(AViewCell)),
                MyViewCellType.B => new DataTemplate(typeof(BViewCell)),
                MyViewCellType.C => new DataTemplate(typeof(CViewCell)),
                _ => new DataTemplate(typeof(DViewCell)),
            };
        }
    }
```

Thank you!

**Comment by adospace** [comment]
Hi, you probably shouldn't use a template selector at all. 
Where are you going to use the template selector? for example, if using a CollectionView just provide a Render function that renders your UI based on the Item.

**Comment by Code-DJ** [comment]
Migrating old code to reactor-maui that uses ListView with DataTemplateSelector. Will switch to CollectionView. Thanks!

**Comment by adospace** [comment]
Yes, you can still use the listview: https://github.com/adospace/reactorui-maui/blob/main/samples/MauiReactor.TestApp/Pages/ListViewExtendedTestPage.cs

**Comment by Code-DJ** [comment]
> Yes, you can still use the listview: https://github.com/adospace/reactorui-maui/blob/main/samples/MauiReactor.TestApp/Pages/ListViewExtendedTestPage.cs

It works. Thank you!

I was overthinking it. The code was crashing when scrolling the ListView but that was due a bug in my code :)
