### ISSUE TITLE
Start hot reload after project run

### ISSUE THREAD

**Issue by MattePozzy** [adospace/reactorui-maui#83]
Hi,
how its possible to run the command to start the hot reload just after the project is built?
I need to run this command `dotnet-maui-reactor -f [net7.0-android|net7.0-ios|net7.0-maccatalyst|windows10.0.19041.0] --mode Full` when a specific platform is selected to build and run.

Thank you.

**Comment by adospace** [comment]
Well, I'm not sure you need to run it just after the project build, I guess you need to run the hot reload when the project runs?
I have a custom command in visual studio (using a custom context menu on the project) that runs the command on the project folder, or I'm missing anything?

**Comment by adospace** [comment]
In Visual Studio create an external tool from Tools->External Tools like this:

Visual Studio external tools dialog
![image](https://github.com/adospace/reactorui-maui/assets/10573253/8d3f42ba-dfb6-4369-a874-1777026c9837)


Add the command to the Solution context menu.
Right-click on the toolbar and select Customize button:



Add a new command and select the correct External Command (in my case was External Command 2):

![image](https://github.com/adospace/reactorui-maui/assets/10573253/d4b33d3d-d4f4-4fa6-9e95-1c04d5727b52)

**Comment by Raystorm7** [comment]
> In Visual Studio create an external tool from Tools->External Tools like this:
> 
> Visual Studio external tools dialog ![image](https://user-images.githubusercontent.com/10573253/244419301-8d3f42ba-dfb6-4369-a874-1777026c9837.png)
> 
> Add the command to the Solution context menu. Right-click on the toolbar and select Customize button:
> 
> Add a new command and select the correct External Command (in my case was External Command 2):
> 
> ![image](https://user-images.githubusercontent.com/10573253/244419560-d4b33d3d-d4f4-4fa6-9e95-1c04d5727b52.png)

Thank you!

**Comment by Code-DJ** [comment]
@adospace you call the External Tools item "Run MauiReactor Hot-Reload (Android)" but that command is to build and run. For hot-reload, don't you also need to run `dotnet-maui-reactor -f net7.0-android` separately?

**Comment by adospace** [comment]
Yes, of course, you're right, this the correct command:

`/c "wt.exe dotnet-maui-reactor -f net7.0-android -d $(ProjectDir)"`

![image](https://github.com/adospace/reactorui-maui/assets/10573253/444be621-4729-4f26-a99b-2d7616246146)
