### ISSUE TITLE
Issue about documentation

### ISSUE THREAD

**Issue by Raystorm7** [adospace/reactorui-maui#84]
Hi,
I'm studying how this repository can work for our new application and I was looking at this doc page:
https://adospace.gitbook.io/mauireactor/components/component-with-children

If I use that code `WithVerticalOrientation`  doesn't exixts and in the `WrapGrid `component I have this issue
`The type 'MauiReactor.VisualNode' cannot be used as type parameter 'T' in the generic type or method 'GridExtensions.GridColumn<T>(T, int)'. There is no implicit reference conversion from 'MauiReactor.VisualNode' to 'MauiReactor.IVisualNodeWithAttachedProperties'.`

How can I fix these issues?

Thank you.

**Comment by adospace** [comment]
WrapGrid is a component defined in the documentation sample, so clearly doesn't have such method.
Not sure what you're achiving but I guess you could add a method like this:

```csharp
public WrapGrid WithVerticalOrientation()
{
    _verticalOrientation = true;
    return this;
}

```

and use `_verticalOrientation `in the render method to arrange controls as you need.
