### ISSUE TITLE
bug in hot reload

### ISSUE THREAD

**Issue by Code-DJ** [adospace/reactorui-maui#87]
Hot reload does not set the DEBUG flag. See example below. On change of any file in the project, hot reload kicks in causing Foo to get recreated but logic doesn't go through `if DEBUG`, writes RELEASE to the console and Bar is set to null.

```csharp
public class Foo
{
    static readonly string Bar;

    static Foo()
    {
#if DEBUG
        Console.WriteLine("DEBUG");
        Bar = "Testing 123";
#else
        Console.WriteLine("RELEASE");
        Bar = null!;
#endif
    }
}
```

**Comment by adospace** [comment]
hum, by default, using the mauireactor template hot-reload is not configured at all under Release mode:
![image](https://github.com/adospace/reactorui-maui/assets/10573253/f8c5e08b-f5c2-45b1-a914-3bb95cf53956)

and running the project in debug the #else branch above shouldn't go in the compile code at all.

are you running the app under Release or Debug? can you post a small project showing the issue?

**Comment by Code-DJ** [comment]
I have it the same way. Changed from static variable and constructor to instance variable and constructor, moved the `#if DEBUG` one level up where the class gets instantiated. Closing thanks!

**Comment by Code-DJ** [comment]
Hi, there is a bug in hot reload - not sure how it works behind the scenes but I assume it builds an loads a new assembly in the background - this assembly is being built in Release mode.

- Created a new project on macOS using `dotnet new maui-reactor-startup`
- I was getting an error in MauiProgram.cs for `app.SetWindowsSpecificAssetsDirectory("Assets");` so removed it. It's anyway not relevant to this issue.
- In MainPage.cs Render method added the following lines:
```csharp
public override VisualNode Render()
{
#if DEBUG
        Console.WriteLine("DEBUG");
#else
        Console.WriteLine("RELEASE");
#endif
/* rest of the code */
}
```
- Ran `dotnet build -t:Run -f net7.0-ios /p:_DeviceName=:v2:udid=EECA5B10-A549-4D07-8A60-0CA944B62766` in terminal.
- Ran `dotnet-maui-reactor -f net7.0-ios`  in another terminal.
- Notice in the first terminal it prints DEBUG each time you click the button.
- Save MainPage.cs (with or without making a change).
- Click the button and notice it print RELEASE.

**Comment by Code-DJ** [comment]
Looks like it is being built in debug mode but the DEBUG constants in not being set `DefineConstants`. Probably Visual Studio automatically does this for us. May be we need to pass it here?

https://github.com/adospace/reactorui-maui/blob/39cb1de97f918854b895a4909d2dcc709cdba55d/src/MauiReactor.HotReloadConsole/HotReloadClientEmit.cs#L55

```csharp
{ "DefineConstants", "DEBUG;TRACE" }
```

https://2000thingscsharp.files.wordpress.com/2012/01/490-001.png

**Comment by adospace** [comment]
Hi, sorry, but can't look at the issue before Wednesday next week, hopefully it is not a problem for you
