### ISSUE TITLE
TabbedPage display empty

### ISSUE THREAD

**Issue by chaoyebugao** [adospace/reactorui-maui#88]
### Problem:
I want a TabbedPage with login and register tabs. But nothing show up In `Windows Machine` when I navigated to it. I don't know what's wrong.

### Steps to reproduce:
1. Add new project with `MauiReactor base app`
2. Add new `LoginTabbedPage` add navigate code to it
3. Start project with `Windows Machine` and click MainPage's button, navigate to it

### Relative Codes:
``` C#
// MainPage button click method
private void HandleClick()
{
    SetState(s => s.Counter++);

    //var navTask = Navigation.PushAsync<LoginPage>();
    //navTask.ContinueWith(t =>
    //{
    //});

    var navTask = Navigation.PushAsync<LoginTabbedPage>();
    navTask.ContinueWith(t =>
    {
    });
}
```

``` C#
// This page no content show up
internal class LoginTabbedPage : Component
{
    public override VisualNode Render()
    {
        return new TabbedPage()
        {
            //new LoginPage(),
            //new RegisterPage(),

            new ContentPage()
            {
                new Label("Label 1"),
            },
            new ContentPage()
            {
                new Label("Label 2"),
            },
        };
    }
}
```

### Solution Codes:
[MauiReactorTabbedDemo.zip](https://github.com/adospace/reactorui-maui/files/11714261/MauiReactorTabbedDemo.zip)

### Versions:
windows 11 -  22H2
Visual Studio 2022 - 17.6.2

### BTW:
There is some wrong generated code with `MauiReactor base app` template tool:
``` C#
// Generated with new project
// app.SetWindowsSpecificAssetsDirectory("Assets");
// Actual method
app.SetWindowsSpecificAssectDirectory("Assets");
```

**Comment by adospace** [comment]
Hi, the MauiReactorTabbedDemo.zip is empty.
Regarding the last question if you upgrade to latest version of MauiReactor you'll find the correct name of the method that is : SetWindowsSpecificAssetsDirectory (previous one had a typo)

**Comment by chaoyebugao** [comment]
> Hi, the MauiReactorTabbedDemo.zip is empty. Regarding the last question if you upgrade to latest version of MauiReactor you'll find the correct name of the method that is : SetWindowsSpecificAssetsDirectory (previous one had a typo)

I've downloaded and opened the zip file. It's not empty, huh, weird~
![image](https://github.com/adospace/reactorui-maui/assets/3005574/3e23a014-08b7-44dd-a174-b49f7fb7d964)

**Comment by chaoyebugao** [comment]
Huh~  Thanks for the tip. I've updated nugets and It worked! Thanks a lot~
